import { useEffect, useMemo, useRef, useState } from 'react';
import { Alert, Button, Empty, Panel, SkeletonRows, Status, Table, buttonClasses } from '@syntra/ui';
import { ApiError, api } from '../../session/api.js';
import { useCan } from '../../session/SessionProvider.js';
import { useApiResource } from './hooks.js';

/**
 * The export center (backlog #48).
 *
 * Every export is generated by a background job, sealed at rest, watermarked
 * with the requester, and downloadable only by them, only until it expires,
 * and only while they still hold the permission it needed. This screen shows
 * where each one stands, offers the download while it is offered, and lets
 * the requester -- or a tenant administrator, for anybody's -- revoke it.
 */

export interface ExportRow {
  id: string;
  kind: string;
  status: 'queued' | 'running' | 'ready' | 'failed' | 'revoked' | 'expired';
  requestedByUserId: string;
  requestedAt: string;
  expiresAt: string | null;
  rowCount: number | null;
  byteLength: number | null;
  sha256: string | null;
  error: string | null;
  downloadCount: number;
}

const KIND: Record<string, string> = {
  audit_log: 'Audit log',
  govern_access: 'Access report',
  support_bundle: 'Support bundle',
};

const TONE: Record<ExportRow['status'], 'neutral' | 'active' | 'warning' | 'danger' | 'inactive'> = {
  queued: 'neutral',
  running: 'warning',
  ready: 'active',
  failed: 'danger',
  revoked: 'inactive',
  expired: 'inactive',
};

const LABEL: Record<ExportRow['status'], string> = {
  queued: 'Queued',
  running: 'Generating',
  ready: 'Ready',
  failed: 'Failed',
  revoked: 'Revoked',
  expired: 'Expired',
};

/**
 * One sentence per status change, the same whether this screen caused it (a
 * revocation) or noticed it on the next poll -- so the two announcements of
 * one revocation cannot say different things.
 */
function describeChange(row: Pick<ExportRow, 'kind' | 'status'>): string {
  const erased = row.status === 'revoked' || row.status === 'expired' ? '; its file has been erased' : '';
  return `${KIND[row.kind] ?? row.kind} export: ${LABEL[row.status].toLowerCase()}${erased}`;
}

/** While anything is still being generated, look again this often. */
const POLL_MS = 3000;

const when = (iso: string | null) =>
  iso === null
    ? '—'
    : new Date(iso).toLocaleString(undefined, {
        month: 'short',
        day: '2-digit',
        hour: '2-digit',
        minute: '2-digit',
      });

const size = (bytes: number | null) =>
  bytes === null ? '—' : bytes < 1024 * 1024 ? `${Math.ceil(bytes / 1024)} KB` : `${(bytes / (1024 * 1024)).toFixed(1)} MB`;

export function ExportsTab() {
  const can = useCan();
  const manageAll = can('tenant.manage');
  const [scope, setScope] = useState<'mine' | 'all'>('mine');
  const { data, error, loading, reload } = useApiResource<{ exports: ExportRow[] }>(
    `/api/admin/exports?scope=${scope}`,
  );
  const [announcement, setAnnouncement] = useState('');
  const [problem, setProblem] = useState<string | null>(null);
  const [busy, setBusy] = useState<string | null>(null);
  const previous = useRef<Map<string, ExportRow['status']>>(new Map());

  const rows = useMemo(() => data?.exports ?? [], [data]);
  const pending = rows.some((row) => row.status === 'queued' || row.status === 'running');

  // Follow a generating export until it settles.
  useEffect(() => {
    if (!pending) return;
    const timer = setTimeout(reload, POLL_MS);
    return () => clearTimeout(timer);
  }, [pending, data, reload]);

  // Say a status change out loud, once, when it happens -- not on first load.
  useEffect(() => {
    const seen = previous.current;
    const changed = rows.filter((row) => seen.has(row.id) && seen.get(row.id) !== row.status);
    if (changed.length > 0) {
      setAnnouncement(changed.map(describeChange).join('. '));
    }
    previous.current = new Map(rows.map((row) => [row.id, row.status]));
  }, [rows]);

  async function revoke(row: ExportRow) {
    setBusy(row.id);
    setProblem(null);
    try {
      await api(`/api/admin/exports/${row.id}/revoke`, { method: 'POST', body: JSON.stringify({}) });
      setAnnouncement(describeChange({ ...row, status: 'revoked' }));
      reload();
    } catch (cause) {
      setProblem(
        cause instanceof ApiError ? (cause.problem.detail ?? cause.problem.title) : 'The export could not be revoked.',
      );
    } finally {
      setBusy(null);
    }
  }

  return (
    <>
      {manageAll && (
        <div className="mb-4 flex gap-2" role="group" aria-label="Whose exports">
          <Button variant={scope === 'mine' ? 'primary' : 'secondary'} aria-pressed={scope === 'mine'} onClick={() => setScope('mine')}>
            Mine
          </Button>
          <Button variant={scope === 'all' ? 'primary' : 'secondary'} aria-pressed={scope === 'all'} onClick={() => setScope('all')}>
            Everyone’s
          </Button>
        </div>
      )}

      <div role="status" aria-live="polite" className="sr-only">
        {announcement}
      </div>
      {problem && (
        <div className="mb-4">
          <Alert tone="danger">{problem}</Alert>
        </div>
      )}
      {error && <Alert tone="danger">{error}</Alert>}

      {!error && (
        <Panel>
          {loading && !data && <SkeletonRows rows={4} cols={5} />}

          {data && rows.length === 0 && (
            <div className="p-6">
              <Empty title="No exports">Export the audit log from its search, or an access report from Governance.</Empty>
            </div>
          )}

          {data && rows.length > 0 && (
            <Table>
              <thead>
                <tr>
                  <th scope="col">Export</th>
                  <th scope="col">Status</th>
                  <th scope="col">Requested</th>
                  <th scope="col">Expires</th>
                  <th scope="col" className="max-lg:hidden">
                    Rows
                  </th>
                  <th scope="col" className="max-lg:hidden">
                    Size
                  </th>
                  <th scope="col" className="max-xl:hidden">
                    SHA-256
                  </th>
                  <th scope="col">
                    <span className="sr-only">Actions</span>
                  </th>
                </tr>
              </thead>
              <tbody>
                {rows.map((row) => (
                  <tr key={row.id}>
                    <td className="text-ink">{KIND[row.kind] ?? row.kind}</td>
                    <td>
                      <Status tone={TONE[row.status]}>{LABEL[row.status]}</Status>
                      {row.status === 'failed' && row.error && <div className="mt-1 text-sm text-danger">{row.error}</div>}
                    </td>
                    <td className="whitespace-nowrap">{when(row.requestedAt)}</td>
                    <td className="whitespace-nowrap">{row.status === 'ready' ? when(row.expiresAt) : '—'}</td>
                    <td className="tabular-nums max-lg:hidden">{row.rowCount ?? '—'}</td>
                    <td className="tabular-nums max-lg:hidden">{size(row.byteLength)}</td>
                    <td className="max-xl:hidden">
                      {row.sha256 ? <code title={row.sha256}>{row.sha256.slice(0, 12)}…</code> : '—'}
                    </td>
                    <td>
                      <div className="flex justify-end gap-2">
                        {row.status === 'ready' && scope === 'mine' && (
                          // A plain link, not a fetch: the browser streams the
                          // file to disk and the session cookie authorises it.
                          <a className={buttonClasses('secondary', 'sm')} href={`/api/admin/exports/${row.id}/download`} download>
                            Download
                          </a>
                        )}
                        {(row.status === 'ready' || row.status === 'queued' || row.status === 'running') && (
                          <Button
                            size="sm"
                            variant="danger-quiet"
                            loading={busy === row.id}
                            onClick={() => void revoke(row)}
                          >
                            Revoke
                          </Button>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </Table>
          )}
        </Panel>
      )}
    </>
  );
}
