import type { FastifyInstance, FastifyRequest } from 'fastify';
import { exportListQuery, exportRequestBody, idParam, type ExportRequestBody } from '@syntra/contracts';
import {
  ExportRefusedError,
  JobNotQueuedError,
  PERMISSIONS,
  downloadExport,
  exportPermissions,
  hasPermission,
  listExports,
  type MasterKeyProvider,
  readExport,
  requestExport,
  revokeExport,
  type ExportKind,
  type ExportRefusal,
  type ExportSummary,
  type Scheduler,
  readableSnapshot,
} from '@syntra/core';
import { ProblemError } from '../../plugins/problem-json.js';
import { requireSession } from '../../plugins/require-session.js';

/**
 * The export center (backlog #48): request, follow, download and revoke
 * asynchronous exports.
 *
 * No route-level `requirePermission`, deliberately. What an export needs
 * depends on its kind -- `audit.read` for the log, `govern.read` and
 * `govern.export` for a Govern report -- and Core's `exportAuthority` is the
 * one place that decides it, at request, at generation and at download. The
 * route adds the half Core cannot see: a machine token's own scopes, which
 * must cover every permission the kind needs (an intersection, as everywhere
 * else).
 */

const STATUS: Record<ExportRefusal, number> = {
  forbidden: 403,
  authority_changed: 403,
  not_found: 404,
  not_ready: 409,
  failed: 409,
  state: 409,
  expired: 410,
  revoked: 410,
};

export function exportProblem(cause: ExportRefusedError): ProblemError {
  return new ProblemError(STATUS[cause.code], `export-${cause.code.replace(/_/g, '-')}`, 'Export refused', cause.message);
}

/** A token narrower than the account cannot take a copy the token was not minted for. */
export function assertTokenCovers(request: FastifyRequest, kind: ExportKind): void {
  const { viaToken, tokenScopes } = request.session;
  if (!viaToken || tokenScopes.length === 0) return;
  const missing = exportPermissions(kind).filter((p) => !tokenScopes.includes(p));
  if (missing.length > 0) {
    throw new ProblemError(403, 'forbidden', 'Forbidden', `Requires ${missing.join(' and ')}`);
  }
}

export function schedulerOr503(scheduler: (() => Scheduler | null) | undefined): Scheduler {
  const running = scheduler?.();
  if (!running) {
    // 503 rather than generating inline. The whole point of the service is
    // that a large export does not hold a request open; a fallback that did
    // would hide a broken deployment behind a button that appears to work.
    throw new ProblemError(
      503,
      'scheduler-unavailable',
      'Background jobs are not running',
      'An export is generated by a background job, and the job scheduler did not start. Check the API log for why pg-boss failed to start.',
    );
  }
  return running;
}

/** Queues an export for the caller, mapping Core's refusals onto problems. */
export async function queueExportFor(
  request: FastifyRequest,
  scheduler: Scheduler,
  body: ExportRequestBody,
): Promise<ExportSummary> {
  assertTokenCovers(request, body.kind);
  // A Govern export names its snapshot; it is looked up (through the one
  // accessor, so "unreadable" is refused too) before anything is queued. It
  // was queued with any id -- another tenant's included -- and failed later in
  // the job, after the caller had been told 202.
  if (body.kind === 'govern_access') {
    const snapshotId = (body.params as { snapshotId?: string }).snapshotId;
    if (snapshotId !== undefined) await request.db((tx) => readableSnapshot(tx, snapshotId));
  }
  try {
    return await requestExport(scheduler, request.tenantId, {
      kind: body.kind,
      params: body.params as Record<string, unknown>,
      ttlHours: body.ttlHours,
      requestedByUserId: request.session.userId,
      requestedViaToken: request.session.viaToken,
      sourceIp: request.ip,
    });
  } catch (cause) {
    if (cause instanceof ExportRefusedError) throw exportProblem(cause);
    if (cause instanceof JobNotQueuedError) {
      throw new ProblemError(
        503,
        'job-not-queued',
        'The export was recorded but not queued',
        `${cause.message}. The export is marked failed; request it again once the job queue is healthy.`,
      );
    }
    throw cause;
  }
}

export async function registerAdminExportRoutes(
  app: FastifyInstance,
  options: { keyProvider: MasterKeyProvider; scheduler?: () => Scheduler | null },
): Promise<void> {
  app.addHook('preHandler', requireSession('admin'));
  const provider = options.keyProvider;

  const managesAll = (request: FastifyRequest) =>
    request.db((tx) => hasPermission(tx, request.session.userId, PERMISSIONS.TENANT_MANAGE));

  app.post('/exports', async (request, reply) => {
    const body = exportRequestBody.parse(request.body ?? {});
    const scheduler = schedulerOr503(options.scheduler);
    const created = await queueExportFor(request, scheduler, body);
    return reply.status(202).send({ export: created });
  });

  app.get('/exports', async (request) => {
    const { scope } = exportListQuery.parse(request.query);
    // Everybody's exports is a tenant administrator's view: it names who took
    // copies of what, which is itself worth protecting.
    if (scope === 'all' && !(await managesAll(request))) {
      throw new ProblemError(403, 'forbidden', 'Forbidden', `Requires ${PERMISSIONS.TENANT_MANAGE}`);
    }
    const exports = await request.db((tx) =>
      listExports(tx, { userId: request.session.userId, all: scope === 'all' }),
    );
    return { exports };
  });

  app.get('/exports/:id', async (request) => {
    const { id } = idParam.parse(request.params);
    const all = await managesAll(request);
    const found = await request.db((tx) =>
      readExport(tx, id, { userId: request.session.userId, all }),
    );
    if (found === null) throw new ProblemError(404, 'not-found', 'Export not found');
    return { export: found };
  });

  app.get('/exports/:id/download', async (request, reply) => {
    const { id } = idParam.parse(request.params);
    // The token check needs the kind, which only the row knows. A token that
    // cannot see the row gets the same 404 Core gives anybody else.
    const summary = await request.db((tx) =>
      readExport(tx, id, { userId: request.session.userId, all: false }),
    );
    if (summary === null) throw new ProblemError(404, 'not-found', 'Export not found');
    assertTokenCovers(request, summary.kind as ExportKind);

    try {
      const file = await downloadExport(request.tenantId, {
        exportId: id,
        userId: request.session.userId,
        provider,
        sourceIp: request.ip,
      });
      return reply
        .header('content-type', file.contentType)
        .header('content-disposition', `attachment; filename="${file.filename}"`)
        .header('x-syntra-export-sha256', file.sha256)
        // A copy of tenant data must not be kept by a proxy or the browser
        // cache past the moment it was handed over; expiry and revocation are
        // only as good as the last copy nobody controls.
        .header('cache-control', 'no-store')
        .send(file.body);
    } catch (cause) {
      if (cause instanceof ExportRefusedError) throw exportProblem(cause);
      throw cause;
    }
  });

  app.post('/exports/:id/revoke', async (request) => {
    const { id } = idParam.parse(request.params);
    const manageAll = await managesAll(request);
    try {
      const revoked = await revokeExport(request.tenantId, {
        exportId: id,
        actorUserId: request.session.userId,
        manageAll,
        sourceIp: request.ip,
      });
      return { export: revoked };
    } catch (cause) {
      if (cause instanceof ExportRefusedError) throw exportProblem(cause);
      throw cause;
    }
  });
}
