import { createHash } from 'node:crypto';
import { withTenant } from '@syntra/db';
import { DATA_INVENTORY, INVENTORY_PROFILES, inventoryEntry } from './inventory.js';
import { collectSubjectData, resolveSubjectIds, rowReplacer } from './subject-data.js';

/**
 * The data-subject access bundle: one JSON document, generated by the export
 * job (`dsar_bundle`), sealed and watermarked like every other export.
 *
 * Every section is one table the data inventory links to the person, carrying
 * the inventory's own description of that data -- what it is for, where it
 * came from, how long it is kept, and the categories of its columns -- beside
 * the rows. Credential material (fields marked secret) is never included, and
 * the bundle says so.
 */

export const DSAR_BUNDLE_SCHEMA = 'syntra.dsar-bundle.v1';

/** A version of the inventory the bundle was built with, so two bundles can be compared. */
export function inventoryFingerprint(): string {
  const shape = Object.values(DATA_INVENTORY).map((e) => [e.model, e.fields.map((f) => `${f.name}:${f.class}${f.secret ? '#' : ''}`)]);
  return createHash('sha256').update(JSON.stringify(shape)).digest('hex').slice(0, 16);
}

export interface BundleParams {
  caseId: string;
  personId: string;
  reference?: string;
}

/**
 * Writes the bundle through `write` (which the export service seals and
 * bounds) and returns the number of rows it carried.
 */
export async function writeSubjectBundle(
  tenantId: string,
  params: BundleParams,
  watermark: Record<string, string>,
  write: (text: string) => void,
): Promise<number> {
  const built = await withTenant(tenantId, async (tx) => {
    const privacyCase = await tx.privacyCase.findFirst({ where: { id: params.caseId } });
    if (privacyCase === null || privacyCase.personId !== params.personId) {
      throw new Error('the privacy case this bundle was requested for no longer names this person');
    }
    const ids = await resolveSubjectIds(tx, params.personId);
    if (ids === null) throw new Error('the person this bundle was requested for does not exist');
    const sections = await collectSubjectData(tx, ids);
    return { privacyCase, ids, sections };
  }, { timeoutMs: 120_000 });

  const excluded = Object.values(DATA_INVENTORY)
    .flatMap((e) => e.fields.filter((f) => f.secret).map((f) => `${e.model}.${f.name}`))
    .sort();
  let rowCount = 0;
  const sections = built.sections.map((section) => {
    const entry = inventoryEntry(section.table);
    const profile = INVENTORY_PROFILES[entry.profile];
    rowCount += section.rows.length;
    return {
      table: section.table,
      area: profile.title,
      purpose: profile.purpose,
      source: profile.source,
      retention: profile.retention,
      legalBasis: profile.legalBasis,
      columns: Object.fromEntries(entry.fields.filter((f) => !f.secret).map((f) => [f.name, f.class])),
      rowCount: section.rows.length,
      rows: section.rows,
    };
  });

  const document = {
    type: 'syntra-dsar-bundle',
    schema: DSAR_BUNDLE_SCHEMA,
    watermark: { ...watermark, case_id: built.privacyCase.id, case_reference: built.privacyCase.reference },
    statement:
      `A copy of the personal data this Syntra tenant holds about one person, taken for data-subject request ${built.privacyCase.reference} by the user named in the watermark. ` +
      'Each section is one table, described by the data inventory: what it is for, where it came from and how long it is kept. The audit section lists the events the person performed and the events about them.',
    inventoryVersion: inventoryFingerprint(),
    case: {
      reference: built.privacyCase.reference,
      requestTypes: built.privacyCase.requestTypes,
      receivedAt: built.privacyCase.receivedAt.toISOString(),
      dueAt: built.privacyCase.dueAt.toISOString(),
    },
    subject: {
      personId: built.ids.personId,
      accountIds: built.ids.userIds,
      targetAccountIds: built.ids.accountIds,
    },
    exclusions: {
      statement: 'Credential material is never copied into a bundle: password hashes, token hashes, recovery-code hashes, key material and encrypted secrets.',
      columns: excluded,
    },
    sections,
    end: { type: 'syntra-export-end', export_id: watermark.export_id, section_count: sections.length, row_count: rowCount },
  };

  const text = JSON.stringify(document, rowReplacer, 2);
  for (let at = 0; at < text.length; at += 64 * 1024) write(text.slice(at, at + 64 * 1024));
  return rowCount;
}
