/**
 * The data inventory (backlog #69): every column of every table, classified.
 *
 * This file is the machine-readable source of truth for what personal data
 * Syntra holds, why, where it comes from, how long it is kept and what a
 * data-subject erasure does to it. Three things are derived from it rather
 * than written separately, so they cannot drift from each other:
 *
 *  - `docs/privacy/data-inventory.md`, rendered by `renderDataInventory()`
 *    (`pnpm privacy:inventory`; a test fails when the committed file is stale);
 *  - the data-subject SEARCH and ACCESS BUNDLE, which read every table whose
 *    entry declares `links` and leave out every field marked `#secret`;
 *  - the ERASURE, which applies each field's `!treatment` to the linked rows of
 *    a `pseudonymize` table and deletes the linked rows of a `delete` table.
 *
 * `inventory.test.ts` compares this against the Prisma schema: a column added
 * to a model without an entry here fails the build, as does an entry for a
 * column that no longer exists. Classifying a new column is therefore part of
 * adding it, which is the only point at which anybody knows what it holds.
 *
 * FIELD SPEC GRAMMAR: `<class>[!<treatment>][#secret]`
 *
 *   class      `none` (not personal data), or a personal-data category:
 *              identity | contact | hr | authentication | audit | operational
 *   treatment  what an erasure does to the field, on a `pseudonymize` table:
 *              `pseudonym`        -> 'erased-<row id>' (unique, so unique
 *                                    indexes on logins and keys still hold)
 *              `pseudonym-email`  -> 'erased-<row id>@erased.invalid'
 *              `clear`            -> NULL, or the empty value of a required
 *                                    column ('' / {} / [])
 *              `literal:<text>`   -> that text
 *   #secret    credential material: never copied into an access bundle.
 *
 * Legal bases are PLACEHOLDERS. The controller -- the organisation running
 * Syntra, not Syntra -- decides them, and a value in code would look like
 * advice. Each profile says what is typical so the reviewer has something to
 * confirm or replace (backlog #13, #79).
 */

export const DATA_CATEGORIES = ['identity', 'contact', 'hr', 'authentication', 'audit', 'operational'] as const;
export type DataCategory = (typeof DATA_CATEGORIES)[number];
export type FieldClass = DataCategory | 'none';

export type ErasureTreatment =
  | { kind: 'pseudonym' }
  | { kind: 'pseudonym-email' }
  | { kind: 'clear' }
  | { kind: 'literal'; value: string };

export interface FieldEntry {
  name: string;
  class: FieldClass;
  treatment: ErasureTreatment | null;
  /** Credential material: never copied into an access bundle. */
  secret: boolean;
}

/**
 * How a table's rows are found for one data subject. Each list names columns
 * holding an id of that kind:
 *
 *   person      the person's id
 *   user        an id of an account linked to the person
 *   account     an id of one of the person's target-system accounts
 *   operation   an id of one of the person's lifecycle operations
 *   step        an id of a step of one of those operations
 *   any         any of the above, or one of the person's contract ids
 *   identifier  one of the person's email addresses or account logins
 */
export interface SubjectLinks {
  person?: string[];
  user?: string[];
  account?: string[];
  operation?: string[];
  step?: string[];
  any?: string[];
  identifier?: string[];
}
export type LinkKind = keyof SubjectLinks;

/**
 * What an erasure does to a linked table's rows.
 *
 *   pseudonymize  the rows stay; every field with a treatment is rewritten
 *   delete        the rows are deleted (credential and transient state only --
 *                 never a directory object: deactivate, never delete)
 *   retain        the rows stay unchanged, for the reason in `why`
 */
export type ErasureMode = 'pseudonymize' | 'delete' | 'retain';

export interface InventoryProfile {
  title: string;
  purpose: string;
  source: string;
  retention: string;
  legalBasis: string;
  access: string;
}

export interface TableEntry {
  model: string;
  profile: InventoryProfileKey;
  fields: FieldEntry[];
  links: SubjectLinks | null;
  erasure: ErasureMode | null;
  why: string | null;
}

const PLACEHOLDER = 'PLACEHOLDER -- to be confirmed by the controller.';

export const INVENTORY_PROFILES = {
  hr: {
    title: 'HR record',
    purpose: 'Know who is employed or engaged, in what role and for how long, so accounts and access can be derived from employment.',
    source: 'HR feeds (person sources), CSV import, and administrators.',
    retention: 'For as long as the person is known to the tenant. Deactivated, never deleted; pseudonymised by a data-subject erasure; removed with the tenant.',
    legalBasis: `${PLACEHOLDER} Typically performance of the employment contract (GDPR art. 6(1)(b)) and legal obligation (6(1)(c)).`,
    access: '`identity.read`; `identity.sensitive.read` for the personal email; `identity.write` / `directory.write` to edit; `privacy.manage`.',
  },
  directory: {
    title: 'Directory account',
    purpose: 'The accounts people sign in with, their attributes and what they are members of.',
    source: 'Administrators, directory sync, SCIM, upstream identity providers (just-in-time).',
    retention: 'For as long as the tenant exists. Deactivated, never deleted; pseudonymised by a data-subject erasure; removed with the tenant.',
    legalBasis: `${PLACEHOLDER} Typically performance of the employment contract (6(1)(b)) and legitimate interests in securing systems (6(1)(f)).`,
    access: '`directory.read`, `directory.write`; `privacy.manage`.',
  },
  authentication: {
    title: 'Authentication',
    purpose: 'Prove who is signing in, keep them signed in, and let them recover access.',
    source: 'The person (enrolment, sign-in) and the product (sessions, tokens).',
    retention: 'While the credential or session is live; sessions and refresh tokens are kept revoked as the evidence that access ended. Removed with the tenant.',
    legalBasis: `${PLACEHOLDER} Typically legitimate interests in securing systems (6(1)(f)).`,
    access: 'The person themselves; `directory.write` for administrative resets; credential material is readable by nobody.',
  },
  protocol: {
    title: 'Protocol state',
    purpose: 'Carry one sign-in, federation or single-logout exchange from start to finish.',
    source: 'The product, during a protocol exchange.',
    retention: 'Minutes to hours: each row expires or is consumed; removed with the tenant.',
    legalBasis: `${PLACEHOLDER} Typically legitimate interests in securing systems (6(1)(f)).`,
    access: 'No administrative screen reads these.',
  },
  provisioning: {
    title: 'Target-system account',
    purpose: 'Know which account each person holds in each connected system, and what it was granted, so access follows employment.',
    source: 'Provisioning runs and the target systems they read.',
    retention: 'For as long as the target is connected. Disabled and archived, never deleted; pseudonymised by a data-subject erasure; removed with the target or tenant.',
    legalBasis: `${PLACEHOLDER} Typically performance of the employment contract (6(1)(b)) and legitimate interests in securing systems (6(1)(f)).`,
    access: '`provision.read`, `provision.manage`; `privacy.manage`.',
  },
  lifecycle: {
    title: 'Lifecycle work',
    purpose: 'Carry out and evidence joiner, mover and leaver work: what was requested, approved and done.',
    source: 'HR events, administrators, and the provisioning engine.',
    retention: 'Removed by the lifecycle retention job once resolved and past the policy (`receiptRetentionDays`, `lifecycleOperationRetentionDays`, `observationRetentionDays`, `simulationRetentionDays`), unless under legal hold.',
    legalBasis: `${PLACEHOLDER} Typically legal obligation and legitimate interests in accountable access management (6(1)(c), 6(1)(f)).`,
    access: '`identity.read` / `provision.read` for the work pages; `privacy.manage`.',
  },
  runs: {
    title: 'Run history',
    purpose: 'Show what an import, sync, provisioning run or sweep proposed and did, so an administrator can review it before it applies and explain it afterwards.',
    source: 'The product, from HR feeds, directories and target systems.',
    retention: 'For as long as the source or target exists; before/after values are cleared by a data-subject erasure; removed with the tenant.',
    legalBasis: `${PLACEHOLDER} Typically legitimate interests in accountable access management (6(1)(f)).`,
    access: '`sync.read`, `provision.read`, `automate.read`.',
  },
  requests: {
    title: 'Access requests and grants',
    purpose: 'Record who asked for which access, who approved it and what was granted, as access-governance evidence.',
    source: 'People requesting access, approvers, and administrators.',
    retention: 'For as long as the tenant exists (governance evidence); free text is cleared by a data-subject erasure; removed with the tenant.',
    legalBasis: `${PLACEHOLDER} Typically legal obligation (e.g. internal-control regimes) and legitimate interests (6(1)(c), 6(1)(f)).`,
    access: '`automate.read`, `automate.manage`; the requester and approvers themselves.',
  },
  notifications: {
    title: 'Notifications',
    purpose: 'Deliver email and webhook notifications about access and lifecycle events.',
    source: 'The product.',
    retention: 'Removed by the lifecycle retention job once sent (`notificationRetentionDays`); removed with the tenant.',
    legalBasis: `${PLACEHOLDER} Typically legitimate interests (6(1)(f)).`,
    access: 'No administrative screen reads message bodies.',
  },
  governance: {
    title: 'Access governance',
    purpose: 'Snapshot who holds what, review and certify it, and record findings and revocations.',
    source: 'Govern snapshots of directories and targets; reviewers and administrators.',
    retention: 'Snapshots and what hangs off them are removed by Govern snapshot retention (`snapshotRetentionDays`); decisions and certifications are governance evidence kept with the tenant.',
    legalBasis: `${PLACEHOLDER} Typically legal obligation (internal-control and audit regimes) and legitimate interests (6(1)(c), 6(1)(f)).`,
    access: '`govern.read` (scopeable), `govern.manage`, `govern.export`.',
  },
  audit: {
    title: 'Audit record',
    purpose: 'A tamper-evident record of who did what, when, from where.',
    source: 'Every administrative and authentication action.',
    retention: 'Immutable to the application. Leaves only through the database-owner archive-and-prune procedure after the tenant\'s `auditRetentionDays`, at or before a verified checkpoint. Kept even after a data-subject erasure and a tenant deletion.',
    legalBasis: `${PLACEHOLDER} Typically legal obligation and legitimate interests in security and accountability (6(1)(c), 6(1)(f)).`,
    access: '`audit.read`.',
  },
  exports: {
    title: 'Exports and saved searches',
    purpose: 'Record who took which copy of tenant data, and keep an administrator\'s saved filters.',
    source: 'Administrators.',
    retention: 'The file is erased 1-72 hours after it is ready; the row is kept as the record of who took what.',
    legalBasis: `${PLACEHOLDER} Typically legitimate interests in accountability (6(1)(f)).`,
    access: 'The requester; `tenant.manage` for everybody\'s.',
  },
  privacy: {
    title: 'Data-subject requests',
    purpose: 'Record a data-subject request, how the requester was verified and what was done about it.',
    source: 'Privacy administrators.',
    retention: 'Kept with the tenant as the evidence the request was handled (accountability, art. 5(2)); removed with the tenant.',
    legalBasis: `${PLACEHOLDER} Typically legal obligation (6(1)(c)).`,
    access: '`privacy.manage`.',
  },
  configuration: {
    title: 'Configuration',
    purpose: 'How the tenant is set up. Not personal data, except columns naming the administrator who changed something or a person given a role in the configuration (classified `identity`).',
    source: 'Administrators.',
    retention: 'For as long as the tenant exists.',
    legalBasis: `${PLACEHOLDER} Only the administrator references are personal data; typically legitimate interests (6(1)(f)).`,
    access: 'The permission of the owning module.',
  },
  secrets: {
    title: 'Secrets and keys',
    purpose: 'Encrypted connector credentials and signing keys.',
    source: 'Administrators and key rotation.',
    retention: 'Until replaced; crypto-erased with the tenant.',
    legalBasis: 'Not personal data.',
    access: 'Nobody reads plaintext; the vault decrypts in process.',
  },
} as const satisfies Record<string, InventoryProfile>;
export type InventoryProfileKey = keyof typeof INVENTORY_PROFILES;

/** Where the data lives and who processes it: the same for every table. */
export const INVENTORY_SCOPE = {
  controller: 'The organisation operating the tenant. Syntra is software; the operator of a deployment is the processor or controller as their contracts say.',
  residency: 'The PostgreSQL database of the deployment, in whatever region the operator runs it. Backups follow the operator\'s backup configuration (see docs/operate.md, Backups).',
  processors: 'Syntra adds no sub-processor. Connectors send data to the target systems and receive it from the sources a tenant configures; outbound email goes through the SMTP relay the operator configures; webhooks go to the endpoints a tenant configures.',
} as const;

function parseField(name: string, spec: string): FieldEntry {
  const secret = spec.endsWith('#secret');
  const body = secret ? spec.slice(0, -'#secret'.length) : spec;
  const bang = body.indexOf('!');
  const cls = (bang === -1 ? body : body.slice(0, bang)) as FieldClass;
  const raw = bang === -1 ? null : body.slice(bang + 1);
  let treatment: ErasureTreatment | null = null;
  if (raw === 'pseudonym' || raw === 'pseudonym-email' || raw === 'clear') treatment = { kind: raw };
  else if (raw !== null && raw.startsWith('literal:')) treatment = { kind: 'literal', value: raw.slice('literal:'.length) };
  else if (raw !== null) throw new Error(`unknown erasure treatment "${raw}" for ${name}`);
  if (cls !== 'none' && !(DATA_CATEGORIES as readonly string[]).includes(cls)) {
    throw new Error(`unknown data class "${cls}" for ${name}`);
  }
  return { name, class: cls, treatment, secret };
}

interface TableOptions {
  links: SubjectLinks;
  erasure: ErasureMode;
  why: string;
}

function table(profile: InventoryProfileKey, fields: Record<string, string>, options?: TableOptions) {
  return {
    profile,
    fields: Object.entries(fields).map(([name, spec]) => parseField(name, spec)),
    links: options?.links ?? null,
    erasure: options?.erasure ?? null,
    why: options?.why ?? null,
  };
}

const RAW = {
  Tenant: table('configuration', {
    id: 'none',
    name: 'none',
    slug: 'none',
    primaryDomain: 'none',
    additionalDomains: 'none',
    status: 'none',
    adminMfaRequired: 'none',
    passwordMinLength: 'none',
    selfEnrolmentEnabled: 'none',
    lockoutThreshold: 'none',
    lockoutWindowMinutes: 'none',
    lockoutDurationMinutes: 'none',
    passwordMaxAgeDays: 'none',
    passwordHistoryDepth: 'none',
    emailOtpEnabled: 'none',
    portalSessionIdleMinutes: 'none',
    portalSessionAbsoluteMinutes: 'none',
    adminSessionIdleMinutes: 'none',
    adminSessionAbsoluteMinutes: 'none',
    adminWebauthnRequired: 'none',
    brandName: 'none',
    brandLogo: 'none',
    brandPrimary: 'none',
    brandAccent: 'none',
    oidcConfigGeneration: 'none',
    createdAt: 'none',
  }),
  LoginLockout: table('authentication', {
    id: 'identity',
    tenantId: 'none',
    userId: 'identity',
    failedCount: 'authentication',
    firstFailedAt: 'authentication',
    lastFailedAt: 'authentication',
    lockedAt: 'authentication',
    lockedUntil: 'authentication',
    updatedAt: 'operational',
  }, {
    links: {user: ['userId']},
    erasure: 'delete',
    why: "Transient authentication state.",
  }),
  OrgUnit: table('configuration', {
    id: 'none',
    tenantId: 'none',
    name: 'none',
    parentId: 'none',
    sourceId: 'none',
    sourceAnchor: 'none',
    status: 'none',
    statusReason: 'none',
  }),
  User: table('directory', {
    id: 'identity',
    tenantId: 'none',
    login: 'identity!pseudonym',
    email: 'contact!pseudonym-email',
    displayName: 'identity!literal:Erased user',
    status: 'operational',
    statusReason: 'operational!literal:erased',
    passwordSource: 'operational',
    passwordSourceHint: 'operational!clear',
    orgUnitId: 'operational',
    personId: 'identity',
    sourceId: 'operational',
    sourceAnchor: 'identity',
    createdAt: 'operational',
    updatedAt: 'operational',
  }, {
    links: {person: ['personId']},
    erasure: 'pseudonymize',
    why: "Accounts are deactivated before an erasure and kept afterwards (deactivate, never delete); login, email and display name are replaced by pseudonyms. The directory anchor is kept so a directory sync recognises the account and the restriction refuses its changes.",
  }),
  Group: table('configuration', {
    id: 'none',
    tenantId: 'none',
    name: 'none',
    description: 'none',
    sourceId: 'none',
    sourceAnchor: 'none',
    status: 'none',
    statusReason: 'none',
  }),
  GroupMembership: table('directory', {
    id: 'identity',
    tenantId: 'none',
    groupId: 'operational',
    userId: 'identity',
  }, {
    links: {user: ['userId']},
    erasure: 'retain',
    why: "Identifiers only. Once the account is pseudonymised, the membership says only that an erased account was a member.",
  }),
  UserAttribute: table('directory', {
    id: 'identity',
    tenantId: 'none',
    userId: 'identity',
    key: 'operational',
    type: 'operational',
    value: 'operational!clear',
  }, {
    links: {user: ['userId']},
    erasure: 'pseudonymize',
    why: "Free-form attribute values are cleared; the keys are tenant configuration.",
  }),
  Person: table('hr', {
    id: 'identity',
    tenantId: 'none',
    givenName: 'identity!literal:Erased',
    familyName: 'identity!literal:Person',
    nameConvention: 'identity',
    businessEmail: 'contact!clear',
    personalEmail: 'contact!clear',
    externalId: 'identity',
    status: 'hr',
    createdAt: 'operational',
    updatedAt: 'operational',
    orgUnitId: 'hr',
    departureOverride: 'hr',
    departureOverrideBy: 'identity',
    departureOverrideNote: 'hr!clear',
    sourceId: 'hr',
    statusReason: 'hr!literal:erased',
    processingRestrictedAt: 'operational',
    processingRestrictedCaseId: 'operational',
    erasedAt: 'operational',
    erasedCaseId: 'operational',
  }, {
    links: {person: ['id']},
    erasure: 'pseudonymize',
    why: "The row is kept so every reference to it still resolves; nothing that identified the person remains on it. `externalId` and the source link are kept so an HR feed that still holds the person recognises the row and is refused by the restriction instead of re-creating them.",
  }),
  Contract: table('hr', {
    id: 'identity',
    tenantId: 'none',
    personId: 'identity',
    sequence: 'hr',
    isPrimary: 'hr',
    startDate: 'hr',
    endDate: 'hr',
    jobTitle: 'hr!clear',
    department: 'hr!clear',
    costCentre: 'hr!clear',
    employer: 'hr!clear',
    location: 'hr!clear',
    managerPersonId: 'hr!clear',
    fte: 'hr!clear',
    externalId: 'hr',
  }, {
    links: {person: ['personId']},
    erasure: 'pseudonymize',
    why: "Employment details are cleared. Dates, sequence and the HR employment id are kept: lifecycle decisions (departure, grace periods) are computed from the dates, and the id stops a feed from re-creating the contract.",
  }),
  AuditEvent: table('audit', {
    id: 'audit',
    tenantId: 'none',
    sequence: 'audit',
    occurredAt: 'audit',
    actorUserId: 'identity',
    action: 'audit',
    targetType: 'audit',
    targetId: 'audit',
    outcome: 'audit',
    sourceIp: 'audit',
    payload: 'audit',
    prevHash: 'audit',
    hash: 'audit',
    correlationId: 'audit',
  }, {
    links: {user: ['actorUserId'], any: ['targetId']},
    erasure: 'retain',
    why: "Immutable to the application (`audit_no_update`, `audit_no_delete`) and hash-chained. Payloads can name the person; they leave through the database-owner archive-and-prune procedure once the tenant's audit retention period ends, at or before a verified checkpoint.",
  }),
  Secret: table('secrets', {
    id: 'none',
    tenantId: 'none',
    name: 'none',
    ciphertext: 'none',
    iv: 'none',
    tag: 'none',
    wrappedDek: 'none',
    dekIv: 'none',
    dekTag: 'none',
    updatedAt: 'none',
  }),
  Role: table('configuration', {
    id: 'none',
    tenantId: 'none',
    name: 'none',
    description: 'none',
    permissions: 'none',
    builtIn: 'none',
  }),
  RoleAssignment: table('directory', {
    id: 'identity',
    tenantId: 'none',
    roleId: 'operational',
    userId: 'identity',
    scopeOrgUnitId: 'operational',
  }, {
    links: {user: ['userId']},
    erasure: 'retain',
    why: "Identifiers only: which role an (erased) account held.",
  }),
  PasswordCredential: table('authentication', {
    id: 'identity',
    tenantId: 'none',
    userId: 'identity',
    hash: 'authentication#secret',
    changedAt: 'authentication',
    mustChange: 'authentication',
    updatedAt: 'operational',
  }, {
    links: {user: ['userId']},
    erasure: 'delete',
    why: "Credential material. A deactivated, erased account has no use for it.",
  }),
  PasswordHistory: table('authentication', {
    id: 'identity',
    tenantId: 'none',
    userId: 'identity',
    hash: 'authentication#secret',
    createdAt: 'operational',
  }, {
    links: {user: ['userId']},
    erasure: 'delete',
    why: "Credential material.",
  }),
  Session: table('authentication', {
    id: 'identity',
    tenantId: 'none',
    userId: 'identity',
    tokenHash: 'authentication#secret',
    scope: 'authentication',
    satisfiedFactor: 'authentication',
    ip: 'authentication!clear',
    userAgent: 'authentication!clear',
    createdAt: 'operational',
    lastSeenAt: 'authentication',
    absoluteExpiresAt: 'authentication',
    revokedAt: 'authentication',
  }, {
    links: {user: ['userId']},
    erasure: 'pseudonymize',
    why: "Kept as the evidence that sessions existed and were ended; the network address and browser are cleared.",
  }),
  ApiToken: table('authentication', {
    id: 'identity',
    tenantId: 'none',
    userId: 'identity',
    name: 'authentication',
    tokenHash: 'authentication#secret',
    scopes: 'authentication',
    expiresAt: 'authentication',
    lastUsedAt: 'authentication',
    revokedAt: 'authentication',
    createdAt: 'operational',
    createdBy: 'authentication',
  }, {
    links: {user: ['userId']},
    erasure: 'retain',
    why: "Machine credentials belong to service accounts; the name is an administrator's label and the token is stored hashed.",
  }),
  DirectorySource: table('configuration', {
    id: 'none',
    tenantId: 'none',
    name: 'none',
    type: 'none',
    config: 'none',
    secretName: 'none',
    schedule: 'none',
    autoApply: 'none',
    deactivationThresholdPercent: 'none',
    enabled: 'none',
    writebackEnabled: 'none',
    writebackPassword: 'none',
    writebackDisable: 'none',
    writebackDelete: 'none',
    lastRunAt: 'none',
    createdAt: 'none',
    updatedAt: 'none',
  }),
  AttributeMapping: table('configuration', {
    id: 'none',
    tenantId: 'none',
    sourceId: 'none',
    objectType: 'none',
    sourceAttribute: 'none',
    targetField: 'none',
    transform: 'none',
    isCorrelation: 'none',
  }),
  SyncRun: table('runs', {
    id: 'identity',
    tenantId: 'none',
    sourceId: 'operational',
    status: 'operational',
    startedAt: 'operational',
    finishedAt: 'operational',
    recordsRead: 'operational',
    requiresConfirmation: 'operational',
    blockedReason: 'operational',
    error: 'operational',
    unresolvedMembers: 'operational',
    mappingFailures: 'operational',
    mappingFailureReasons: 'operational',
    cancelState: 'operational',
    cancelRequestedAt: 'operational',
    cancelRequestedByUserId: 'identity',
    cancelResolvedAt: 'operational',
  }),
  SyncChange: table('runs', {
    id: 'identity',
    tenantId: 'none',
    runId: 'operational',
    changeType: 'operational',
    targetType: 'operational',
    targetId: 'operational',
    sourceAnchor: 'operational',
    before: 'operational!clear',
    after: 'operational!clear',
    status: 'operational',
    message: 'operational!clear',
  }, {
    links: {any: ['targetId']},
    erasure: 'pseudonymize',
    why: "Kept as the record of what a sync did; the before and after values are cleared.",
  }),
  PersonSource: table('configuration', {
    id: 'none',
    tenantId: 'none',
    name: 'none',
    type: 'none',
    config: 'none',
    secretName: 'none',
    feedMode: 'none',
    schedule: 'none',
    autoApply: 'none',
    deactivationThresholdPercent: 'none',
    enabled: 'none',
    lastRunAt: 'none',
    createdAt: 'none',
    updatedAt: 'none',
  }),
  PersonFieldMapping: table('configuration', {
    id: 'none',
    tenantId: 'none',
    sourceId: 'none',
    recordType: 'none',
    sourceColumn: 'none',
    targetField: 'none',
    transform: 'none',
    isCorrelation: 'none',
  }),
  PersonImportRun: table('runs', {
    id: 'identity',
    tenantId: 'none',
    sourceId: 'operational',
    status: 'operational',
    startedAt: 'operational',
    finishedAt: 'operational',
    recordsRead: 'operational',
    requiresConfirmation: 'operational',
    blockedReason: 'operational',
    error: 'operational',
    mappingFailures: 'operational',
    mappingFailureReasons: 'operational',
    personsAbsent: 'operational',
    confirmedBy: 'identity',
    cancelState: 'operational',
    cancelRequestedAt: 'operational',
    cancelRequestedByUserId: 'identity',
    cancelResolvedAt: 'operational',
  }),
  PersonImportChange: table('runs', {
    id: 'identity',
    tenantId: 'none',
    runId: 'operational',
    changeType: 'operational',
    recordType: 'operational',
    targetId: 'operational',
    externalId: 'identity',
    before: 'operational!clear',
    after: 'operational!clear',
    status: 'operational',
    message: 'operational!clear',
  }, {
    links: {any: ['targetId']},
    erasure: 'pseudonymize',
    why: "Kept as the record of what an import did; the before and after values and the message are cleared.",
  }),
  AuthPolicy: table('configuration', {
    id: 'none',
    tenantId: 'none',
    defaultOutcome: 'none',
    defaultFactorType: 'none',
    updatedAt: 'none',
  }),
  AuthPolicyRule: table('configuration', {
    id: 'none',
    tenantId: 'none',
    policyId: 'none',
    position: 'none',
    name: 'none',
    enabled: 'none',
    outcome: 'none',
    factorType: 'none',
    applicationIds: 'none',
    groupIds: 'none',
    contractField: 'none',
    contractValues: 'none',
    ipRanges: 'none',
    devicePlatforms: 'none',
    countries: 'none',
    daysOfWeek: 'none',
    startMinute: 'none',
    endMinute: 'none',
    timezone: 'none',
    upstreamIdpId: 'none',
    loginDomains: 'none',
  }),
  Application: table('configuration', {
    id: 'none',
    tenantId: 'none',
    name: 'none',
    slug: 'none',
    description: 'none',
    iconUrl: 'none',
    launchUrl: 'none',
    type: 'none',
    category: 'none',
    catalogKey: 'none',
    visibility: 'none',
    status: 'none',
    createdAt: 'none',
    updatedAt: 'none',
  }),
  AccountPlacement: table('provisioning', {
    id: 'identity',
    tenantId: 'none',
    personId: 'identity',
    targetSystemId: 'operational',
    container: 'operational',
    reason: 'operational',
    movedByUserId: 'identity',
    createdAt: 'operational',
    updatedAt: 'operational',
  }, {
    links: {person: ['personId']},
    erasure: 'retain',
    why: "The container (organisational unit) an account is placed in; not about the person beyond their unit.",
  }),
  OrgUnitContainer: table('configuration', {
    id: 'none',
    tenantId: 'none',
    orgUnitId: 'none',
    targetSystemId: 'none',
    dn: 'none',
    anchor: 'none',
    state: 'none',
    createdAt: 'none',
    updatedAt: 'none',
  }),
  AppAssignment: table('directory', {
    id: 'identity',
    tenantId: 'none',
    applicationId: 'operational',
    subjectType: 'operational',
    userId: 'identity',
    groupId: 'operational',
    orgUnitId: 'operational',
    createdAt: 'operational',
  }, {
    links: {user: ['userId']},
    erasure: 'retain',
    why: "Identifiers only.",
  }),
  EmailOtpCredential: table('authentication', {
    id: 'identity',
    tenantId: 'none',
    userId: 'identity',
    confirmedAt: 'authentication',
    codeHash: 'authentication#secret',
    expiresAt: 'authentication',
    attempts: 'authentication',
    sentAt: 'authentication',
    createdAt: 'operational',
    updatedAt: 'operational',
  }, {
    links: {user: ['userId']},
    erasure: 'delete',
    why: "Credential material.",
  }),
  TotpCredential: table('authentication', {
    id: 'identity',
    tenantId: 'none',
    userId: 'identity',
    secretName: 'authentication',
    algorithm: 'authentication',
    digits: 'authentication',
    period: 'authentication',
    lastCounter: 'authentication',
    confirmedAt: 'authentication',
    createdAt: 'operational',
  }, {
    links: {user: ['userId']},
    erasure: 'delete',
    why: "Credential material; the vault secret it names is deleted with it.",
  }),
  WebAuthnCredential: table('authentication', {
    id: 'identity',
    tenantId: 'none',
    userId: 'identity',
    credentialId: 'authentication#secret',
    publicKey: 'authentication#secret',
    counter: 'authentication',
    transports: 'authentication',
    attestationType: 'authentication',
    rpId: 'authentication',
    label: 'authentication',
    createdAt: 'operational',
    lastUsedAt: 'authentication',
  }, {
    links: {user: ['userId']},
    erasure: 'delete',
    why: "Credential material, including the device label the person typed.",
  }),
  WebAuthnChallenge: table('protocol', {
    id: 'identity',
    tenantId: 'none',
    userId: 'identity',
    purpose: 'authentication',
    challenge: 'authentication#secret',
    expiresAt: 'authentication',
    consumedAt: 'authentication',
    createdAt: 'operational',
  }, {
    links: {user: ['userId']},
    erasure: 'delete',
    why: "Transient protocol state.",
  }),
  RecoveryCode: table('authentication', {
    id: 'identity',
    tenantId: 'none',
    userId: 'identity',
    codeHash: 'authentication#secret',
    usedAt: 'authentication',
    createdAt: 'operational',
  }, {
    links: {user: ['userId']},
    erasure: 'delete',
    why: "Credential material.",
  }),
  PasswordResetToken: table('authentication', {
    id: 'identity',
    tenantId: 'none',
    userId: 'identity',
    tokenHash: 'authentication#secret',
    expiresAt: 'authentication',
    consumedAt: 'authentication',
    createdAt: 'operational',
  }, {
    links: {user: ['userId']},
    erasure: 'delete',
    why: "Credential material.",
  }),
  AuthAttempt: table('protocol', {
    id: 'identity',
    tenantId: 'none',
    userId: 'identity',
    tokenHash: 'authentication#secret',
    applicationId: 'authentication',
    sourceIp: 'authentication!clear',
    purpose: 'authentication',
    scope: 'authentication',
    requiredOutcome: 'authentication',
    requiredFactor: 'authentication',
    ruleId: 'authentication',
    expiresAt: 'authentication',
    consumedAt: 'authentication',
    createdAt: 'operational',
  }, {
    links: {user: ['userId']},
    erasure: 'pseudonymize',
    why: "Kept until it expires; the source address is cleared.",
  }),
  RefreshToken: table('authentication', {
    id: 'identity',
    tenantId: 'none',
    userId: 'identity',
    tokenHash: 'authentication#secret',
    clientId: 'authentication',
    scope: 'authentication',
    createdAt: 'operational',
    absoluteExpiresAt: 'authentication',
    revokedAt: 'authentication',
  }, {
    links: {user: ['userId']},
    erasure: 'retain',
    why: "Stored hashed; kept revoked as the evidence that access ended, like sessions.",
  }),
  SamlConfig: table('configuration', {
    id: 'none',
    tenantId: 'none',
    applicationId: 'none',
    spEntityId: 'none',
    acsUrls: 'none',
    defaultAcsUrl: 'none',
    acsBinding: 'none',
    nameIdFormat: 'none',
    nameIdClaim: 'none',
    spCertificates: 'none',
    wantAuthnRequestsSigned: 'none',
    encryptAssertions: 'none',
    encryptionCertificate: 'none',
    sloUrl: 'none',
    sloBinding: 'none',
    allowIdpInitiated: 'none',
    assertionLifetimeMs: 'none',
    wsFedEnabled: 'none',
    createdAt: 'none',
    updatedAt: 'none',
  }),
  OidcClient: table('configuration', {
    id: 'none',
    tenantId: 'none',
    applicationId: 'none',
    clientId: 'none',
    clientSecretHash: 'none',
    redirectUris: 'none',
    postLogoutRedirectUris: 'none',
    backchannelLogoutUri: 'none',
    backchannelLogoutSessionRequired: 'none',
    grantTypes: 'none',
    clientCredentialsEnabled: 'none',
    scopes: 'none',
    requirePkce: 'none',
    tokenEndpointAuthMethod: 'none',
    idTokenSignedResponseAlg: 'none',
    accessTokenTtlSeconds: 'none',
    refreshTokenTtlSeconds: 'none',
    createdAt: 'none',
    updatedAt: 'none',
  }),
  LogoutDelivery: table('protocol', {
    id: 'identity',
    tenantId: 'none',
    clientId: 'authentication',
    userId: 'identity',
    sessionId: 'authentication',
    attempts: 'authentication',
    nextAttemptAt: 'authentication',
    deliveredAt: 'authentication',
    lastStatus: 'authentication',
    lastError: 'authentication',
    createdAt: 'operational',
  }, {
    links: {user: ['userId']},
    erasure: 'retain',
    why: "Identifiers only: which relying party was told the session ended.",
  }),
  ClaimMappingSet: table('configuration', {
    id: 'none',
    tenantId: 'none',
    name: 'none',
    description: 'none',
    protocol: 'none',
    mappings: 'none',
    createdAt: 'none',
    updatedAt: 'none',
  }),
  ClaimMapping: table('configuration', {
    id: 'none',
    tenantId: 'none',
    applicationId: 'none',
    protocol: 'none',
    claimName: 'none',
    nameFormat: 'none',
    sourceKind: 'none',
    sourceField: 'none',
    contractStrategy: 'none',
    literalValue: 'none',
    releaseScope: 'none',
    multiValued: 'none',
    createdAt: 'none',
  }),
  UpstreamIdp: table('configuration', {
    id: 'none',
    tenantId: 'none',
    slug: 'none',
    name: 'none',
    protocol: 'none',
    enabled: 'none',
    issuerUrl: 'none',
    clientId: 'none',
    clientSecretName: 'none',
    scopes: 'none',
    idpEntityId: 'none',
    ssoUrl: 'none',
    idpSloUrl: 'none',
    ssoBinding: 'none',
    idpCertificates: 'none',
    wantAssertionsSigned: 'none',
    loginAttribute: 'none',
    emailAttribute: 'none',
    displayNameAttribute: 'none',
    groupsAttribute: 'none',
    createUsers: 'none',
    allowLoginAdoption: 'none',
    refreshOnLogin: 'none',
    defaultOrgUnitId: 'none',
    createdAt: 'none',
    updatedAt: 'none',
  }),
  UpstreamLink: table('authentication', {
    id: 'identity',
    tenantId: 'none',
    upstreamIdpId: 'authentication',
    userId: 'identity',
    subject: 'identity!pseudonym',
    lastLoginAt: 'authentication',
    createdAt: 'operational',
  }, {
    links: {user: ['userId']},
    erasure: 'pseudonymize',
    why: "The upstream provider's subject identifier is replaced by a pseudonym so the binding can no longer be used to recognise the person.",
  }),
  FederationRequest: table('protocol', {
    id: 'identity',
    tenantId: 'none',
    upstreamIdpId: 'authentication',
    state: 'authentication',
    expectedResponseTo: 'authentication',
    browserBinding: 'authentication',
    verifierName: 'authentication',
    returnTo: 'authentication',
    applicationId: 'authentication',
    createdAt: 'operational',
    expiresAt: 'authentication',
    consumedAt: 'authentication',
  }),
  SigningKey: table('secrets', {
    id: 'none',
    tenantId: 'none',
    kind: 'none',
    kid: 'none',
    alg: 'none',
    publicJwk: 'none',
    certificate: 'none',
    secretName: 'none',
    status: 'none',
    notBefore: 'none',
    notAfter: 'none',
    retiredAt: 'none',
    createdAt: 'none',
  }),
  OidcArtifact: table('protocol', {
    id: 'identity',
    tenantId: 'none',
    model: 'authentication',
    artifactId: 'authentication',
    uid: 'authentication',
    userCode: 'authentication',
    grantId: 'authentication',
    accountId: 'identity',
    payload: 'authentication',
    expiresAt: 'authentication',
    consumedAt: 'authentication',
    createdAt: 'operational',
  }, {
    links: {user: ['accountId']},
    erasure: 'delete',
    why: "Transient protocol artifacts whose payload can carry claims (names, email).",
  }),
  SamlSsoSession: table('protocol', {
    id: 'identity',
    tenantId: 'none',
    sessionId: 'authentication',
    applicationId: 'authentication',
    nameId: 'identity!pseudonym',
    sessionIndex: 'authentication',
    createdAt: 'operational',
    endedAt: 'authentication',
  }, {
    links: {identifier: ['nameId']},
    erasure: 'pseudonymize',
    why: "The NameID asserted to the service provider is replaced by a pseudonym.",
  }),
  AuthorizationDecision: table('protocol', {
    id: 'identity',
    tenantId: 'none',
    userId: 'identity',
    clientId: 'authentication',
    interactionUid: 'authentication',
    satisfiedFactor: 'authentication',
    createdAt: 'operational',
    expiresAt: 'authentication',
    consumedAt: 'authentication',
  }, {
    links: {user: ['userId']},
    erasure: 'delete',
    why: "Transient protocol state.",
  }),
  SamlAuthnRequest: table('protocol', {
    id: 'identity',
    tenantId: 'none',
    applicationId: 'authentication',
    handle: 'authentication',
    requestId: 'authentication',
    acsUrl: 'authentication',
    relayState: 'authentication',
    protocol: 'authentication',
    forceAuthn: 'authentication',
    browserBinding: 'authentication',
    createdAt: 'operational',
    expiresAt: 'authentication',
    consumedAt: 'authentication',
  }),
  TargetSystem: table('configuration', {
    id: 'none',
    tenantId: 'none',
    name: 'none',
    type: 'none',
    config: 'none',
    secretName: 'none',
    pairedDirectorySourceId: 'none',
    schedule: 'none',
    autoApply: 'none',
    enabled: 'none',
    externalWritesPausedAt: 'none',
    externalWritesPausedByUserId: 'identity',
    externalWritesPauseReason: 'none',
    externalWritesPauseExpiresAt: 'none',
    externalWritesResumedAt: 'none',
    externalWritesResumedByUserId: 'identity',
    maintenanceWindowEnabled: 'none',
    maintenanceWindowDays: 'none',
    maintenanceWindowStartMinute: 'none',
    maintenanceWindowDurationMinutes: 'none',
    adapterChannel: 'none',
    adapterVersionPin: 'none',
    adapterRollbackVersion: 'none',
    adapterSelectionChangedAt: 'none',
    adapterSelectionChangedByUserId: 'identity',
    adapterSelectionReason: 'none',
    deprecationOverrideVersion: 'none',
    deprecationOverrideReason: 'none',
    deprecationOverrideAt: 'none',
    deprecationOverrideExpiresAt: 'none',
    deprecationOverrideByUserId: 'identity',
    enforcementMode: 'none',
    preHireDays: 'none',
    entitlementRevocationDelayDays: 'none',
    disableGraceDays: 'none',
    archiveAfterDays: 'none',
    reenableWithoutConfirmationDays: 'none',
    createAccountThresholdPercent: 'none',
    disableAccountThresholdPercent: 'none',
    archiveAccountThresholdPercent: 'none',
    revokeEntitlementThresholdPercent: 'none',
    deactivateSyntraUserThresholdPercent: 'none',
    perEntitlementThresholdPercent: 'none',
    personPopulationDropPercent: 'none',
    maxContainerCreatesPerRun: 'none',
    maxAttempts: 'none',
    concurrency: 'none',
    renameEnabled: 'none',
    lastRunAt: 'none',
    lastAppliedRunAt: 'none',
    consecutiveSkippedRuns: 'none',
    lastSkippedAt: 'none',
    lastSkipReason: 'none',
    createdAt: 'none',
    updatedAt: 'none',
  }),
  AccountProfile: table('configuration', {
    id: 'none',
    tenantId: 'none',
    targetSystemId: 'none',
    correlationKeyTemplate: 'none',
    uniquenessStrategy: 'none',
    maxUniquenessAttempts: 'none',
    containerTemplate: 'none',
    fallbackContainer: 'none',
    attributeTemplates: 'none',
    initialPasswordPolicy: 'none',
    initialPasswordDelivery: 'none',
    sensitiveApprovalReason: 'none',
    sensitiveApprovedByUserId: 'identity',
    sensitiveApprovedAt: 'none',
    createdAt: 'none',
    updatedAt: 'none',
  }),
  BusinessRule: table('configuration', {
    id: 'none',
    tenantId: 'none',
    targetSystemId: 'none',
    name: 'none',
    description: 'none',
    condition: 'none',
    grantsAccount: 'none',
    enabled: 'none',
    createdAt: 'none',
    updatedAt: 'none',
  }),
  RuleEntitlement: table('configuration', {
    id: 'none',
    tenantId: 'none',
    ruleId: 'none',
    entitlementId: 'none',
  }),
  Entitlement: table('configuration', {
    id: 'none',
    tenantId: 'none',
    targetSystemId: 'none',
    externalId: 'none',
    dn: 'none',
    type: 'none',
    displayName: 'identity',
    description: 'none',
    status: 'none',
    holderCount: 'none',
    requestable: 'none',
    lastSeenAt: 'none',
    manageable: 'none',
    unmanageableReason: 'none',
    membershipKind: 'none',
    privileged: 'none',
    createdAt: 'none',
    updatedAt: 'none',
  }),
  TargetAccount: table('provisioning', {
    id: 'identity',
    tenantId: 'none',
    targetSystemId: 'operational',
    personId: 'identity',
    anchor: 'identity',
    correlationKey: 'identity!pseudonym',
    status: 'operational',
    statusReason: 'operational!clear',
    disabledAt: 'operational',
    disableDueAt: 'operational',
    archiveDueAt: 'operational',
    createdActionId: 'operational',
    lastReconciledAt: 'operational',
    lastAppliedAttributes: 'operational!clear',
    createdAt: 'operational',
    updatedAt: 'operational',
  }, {
    links: {person: ['personId']},
    erasure: 'pseudonymize',
    why: "Accounts are disabled or archived before an erasure. The login Syntra generated and the attributes it last wrote are replaced; the target's immutable object id is kept so a later run recognises the account. The copy in the target system itself must be erased there: Syntra has no delete path to a target, by design.",
  }),
  AccountEntitlement: table('provisioning', {
    id: 'identity',
    tenantId: 'none',
    accountId: 'identity',
    entitlementId: 'operational',
    origin: 'operational',
    grantedByRuleId: 'operational',
    grantedByRequestId: 'operational',
    grantedAt: 'operational',
    revokedAt: 'operational',
    state: 'operational',
  }, {
    links: {account: ['accountId']},
    erasure: 'retain',
    why: "Identifiers only: what an (erased) account held.",
  }),
  PersonProvisionReceipt: table('lifecycle', {
    id: 'identity',
    tenantId: 'none',
    personId: 'identity',
    targetSystemId: 'operational',
    requestKey: 'operational',
    targetName: 'operational',
    status: 'operational',
    jobId: 'operational',
    runId: 'operational',
    runIds: 'operational',
    evidence: 'operational!clear',
    message: 'operational!clear',
    createdAt: 'operational',
    updatedAt: 'operational',
  }, {
    links: {person: ['personId']},
    erasure: 'pseudonymize',
    why: "Kept for its status and target; the evidence and message, which can name the person, are cleared.",
  }),
  LifecycleOperation: table('lifecycle', {
    id: 'identity',
    tenantId: 'none',
    personId: 'identity',
    kind: 'operational',
    idempotencyKey: 'operational',
    status: 'operational',
    attempt: 'operational',
    input: 'operational!clear',
    inputFingerprint: 'operational',
    ownerUserId: 'identity',
    priority: 'operational',
    dueAt: 'operational',
    acknowledgedAt: 'operational',
    startedAt: 'operational',
    completedAt: 'operational',
    approvalRequired: 'operational',
    approvalReason: 'operational!clear',
    requestedByUserId: 'identity',
    approvedAt: 'operational',
    approvedByUserId: 'identity',
    rejectedAt: 'operational',
    rejectedByUserId: 'identity',
    rejectionReason: 'operational!clear',
    sloMinutes: 'operational',
    sloDeadlineAt: 'operational',
    sloBreachedAt: 'operational',
    escalatedAt: 'operational',
    escalatedToUserId: 'identity',
    caseStatus: 'operational',
    resolvedAt: 'operational',
    resolvedByUserId: 'identity',
    resolutionCode: 'operational',
    resolutionSummary: 'operational!clear',
    createdAt: 'operational',
    updatedAt: 'operational',
  }, {
    links: {person: ['personId']},
    erasure: 'pseudonymize',
    why: "Resolved operations are kept as the record that the work happened (retention removes them later); the input payload, which carries HR fields, is cleared.",
  }),
  LifecycleStep: table('lifecycle', {
    id: 'identity',
    tenantId: 'none',
    operationId: 'operational',
    key: 'operational',
    title: 'operational',
    position: 'operational',
    required: 'operational',
    status: 'operational',
    message: 'operational!clear',
    evidence: 'operational!clear',
    responseCategory: 'operational',
    startedAt: 'operational',
    completedAt: 'operational',
    createdAt: 'operational',
    updatedAt: 'operational',
  }, {
    links: {operation: ['operationId']},
    erasure: 'pseudonymize',
    why: "Evidence and messages are cleared.",
  }),
  LifecycleObservation: table('lifecycle', {
    id: 'identity',
    tenantId: 'none',
    stepId: 'operational',
    targetSystemId: 'operational',
    completeness: 'operational',
    matches: 'operational',
    expected: 'operational',
    observed: 'operational',
    differences: 'operational',
    fingerprint: 'operational',
    observedAt: 'operational',
    expiresAt: 'operational',
  }, {
    links: {step: ['stepId']},
    erasure: 'delete',
    why: "What a target reported for the person's account; retention removes these anyway.",
  }),
  LifecycleStepAttempt: table('lifecycle', {
    id: 'identity',
    tenantId: 'none',
    operationId: 'operational',
    stepId: 'operational',
    stepKey: 'operational',
    attempt: 'operational',
    status: 'operational',
    message: 'operational!clear',
    evidence: 'operational!clear',
    responseCategory: 'operational',
    startedAt: 'operational',
    completedAt: 'operational',
    recordedAt: 'operational',
  }, {
    links: {operation: ['operationId']},
    erasure: 'pseudonymize',
    why: "Evidence and messages are cleared.",
  }),
  LifecyclePolicy: table('configuration', {
    id: 'none',
    tenantId: 'none',
    requireApprovalForAccountCreation: 'none',
    requireApprovalForPrivilegedGroups: 'none',
    privilegedGroupPatterns: 'none',
    requireApprovalForUrgentDeparture: 'none',
    requireApprovalForBulkRequeue: 'none',
    bulkRequeueThreshold: 'none',
    maxConcurrentTargetOperations: 'none',
    urgentLeaverSloMinutes: 'none',
    onboardSloHours: 'none',
    moveSloHours: 'none',
    offboardSloHours: 'none',
    escalationOwnerUserId: 'identity',
    notifyOnFailure: 'none',
    notifyOnOverdue: 'none',
    notifyOnAccessBlocked: 'none',
    receiptRetentionDays: 'none',
    observationRetentionDays: 'none',
    notificationRetentionDays: 'none',
    simulationRetentionDays: 'none',
    lifecycleOperationRetentionDays: 'none',
    auditRetentionDays: 'none',
    updatedByUserId: 'identity',
    createdAt: 'none',
    updatedAt: 'none',
  }),
  PersonSourceLink: table('hr', {
    id: 'identity',
    tenantId: 'none',
    sourceId: 'hr',
    personId: 'identity',
    externalId: 'identity',
    linkedByUserId: 'identity',
    linkedAt: 'hr',
  }, {
    links: {person: ['personId']},
    erasure: 'retain',
    why: "The HR source's key for the person. Kept so the feed recognises the row and cannot re-create an erased person while the source still holds them.",
  }),
  IdentityReferenceValue: table('configuration', {
    id: 'none',
    tenantId: 'none',
    kind: 'none',
    value: 'none',
    normalizedValue: 'none',
    active: 'none',
    createdByUserId: 'identity',
    createdAt: 'none',
    updatedAt: 'none',
  }),
  PersonDuplicateReview: table('runs', {
    id: 'identity',
    tenantId: 'none',
    runId: 'operational',
    changeId: 'operational',
    candidatePersonId: 'identity',
    matchKind: 'operational',
    matchedValue: 'operational!literal:[erased]',
    status: 'operational',
    resolution: 'operational',
    note: 'operational!clear',
    reviewedByUserId: 'identity',
    reviewedAt: 'operational',
    restoreStatus: 'operational',
    restoreBlockedReason: 'operational',
    restoreRequiresConfirmation: 'operational',
    createdAt: 'operational',
  }, {
    links: {person: ['candidatePersonId']},
    erasure: 'pseudonymize',
    why: "The matched value (a name or address) and the reviewer's note are cleared.",
  }),
  LifecycleCaseEvent: table('lifecycle', {
    id: 'identity',
    tenantId: 'none',
    operationId: 'operational',
    kind: 'operational',
    actorUserId: 'identity',
    message: 'operational!clear',
    metadata: 'operational!clear',
    createdAt: 'operational',
  }, {
    links: {operation: ['operationId']},
    erasure: 'pseudonymize',
    why: "Messages and metadata are cleared.",
  }),
  LifecycleLegalHold: table('lifecycle', {
    id: 'identity',
    tenantId: 'none',
    subjectType: 'operational',
    subjectId: 'operational',
    reference: 'operational',
    reason: 'operational',
    placedByUserId: 'identity',
    placedAt: 'operational',
    releasedByUserId: 'identity',
    releasedAt: 'operational',
  }, {
    links: {any: ['subjectId']},
    erasure: 'retain',
    why: "A preservation order. An active one refuses the erasure; a released one is the record of it.",
  }),
  TenantExternalWriteStop: table('configuration', {
    id: 'none',
    tenantId: 'none',
    pausedAt: 'none',
    pausedByUserId: 'identity',
    pauseReason: 'none',
    pauseExpiresAt: 'none',
    resumedAt: 'none',
    resumedByUserId: 'identity',
    updatedAt: 'none',
  }),
  TenantDeletionRequest: table('configuration', {
    id: 'none',
    tenantId: 'none',
    status: 'none',
    assessmentDigest: 'none',
    assessmentAuditEventId: 'none',
    exportDigest: 'none',
    exportAuditEventId: 'none',
    dataRevision: 'none',
    reason: 'none',
    requestedByUserId: 'identity',
    requestedAt: 'none',
    approvalExpiresAt: 'none',
    approvedByUserId: 'identity',
    approvedAt: 'none',
    approverStepUpAt: 'none',
    executeNotBefore: 'none',
    executeBefore: 'none',
    executedByUserId: 'identity',
    executorStepUpAt: 'none',
    completedAt: 'none',
    cancelledByUserId: 'identity',
    cancelledAt: 'none',
    closedReason: 'none',
    receipt: 'none',
  }),
  LifecycleSimulation: table('lifecycle', {
    id: 'identity',
    tenantId: 'none',
    kind: 'operational',
    scope: 'operational',
    personId: 'identity',
    department: 'operational',
    input: 'operational',
    result: 'operational',
    peopleCount: 'operational',
    writesPerformed: 'operational',
    createdByUserId: 'identity',
    createdAt: 'operational',
    expiresAt: 'operational',
  }, {
    links: {person: ['personId']},
    erasure: 'delete',
    why: "A rehearsal; retention removes these anyway.",
  }),
  ConnectionReadinessCheck: table('configuration', {
    id: 'none',
    tenantId: 'none',
    systemKind: 'none',
    systemId: 'none',
    configurationFingerprint: 'none',
    capabilities: 'none',
    status: 'none',
    latencyMs: 'none',
    message: 'none',
    actorUserId: 'identity',
    checkedAt: 'none',
  }),
  ProvisionRun: table('runs', {
    id: 'identity',
    tenantId: 'none',
    targetSystemId: 'operational',
    status: 'operational',
    startedAt: 'operational',
    finishedAt: 'operational',
    lastProgressAt: 'operational',
    createAccountCount: 'operational',
    updateAccountCount: 'operational',
    enableAccountCount: 'operational',
    disableAccountCount: 'operational',
    archiveAccountCount: 'operational',
    renameAccountCount: 'operational',
    grantEntitlementCount: 'operational',
    revokeEntitlementCount: 'operational',
    deactivateSyntraUserCount: 'operational',
    reactivateSyntraUserCount: 'operational',
    personsEvaluated: 'operational',
    personsWithActiveContract: 'operational',
    personsUnprocessable: 'operational',
    accountsReadFromTarget: 'operational',
    entitlementsReadFromTarget: 'operational',
    requiresConfirmation: 'operational',
    blockedReason: 'operational',
    confirmedByUserId: 'identity',
    error: 'operational',
    cancelState: 'operational',
    cancelRequestedAt: 'operational',
    cancelRequestedByUserId: 'identity',
    cancelResolvedAt: 'operational',
    adapterVersion: 'operational',
    capabilityRefusedCount: 'operational',
    capabilityRefusal: 'operational',
  }),
  ProvisionAction: table('runs', {
    id: 'identity',
    tenantId: 'none',
    runId: 'operational',
    actionType: 'operational',
    personId: 'identity',
    accountId: 'identity',
    entitlementId: 'operational',
    before: 'operational!clear',
    after: 'operational!clear',
    attributedRuleIds: 'operational',
    revocationOrderId: 'operational',
    grantId: 'operational',
    sequence: 'operational',
    status: 'operational',
    attempts: 'operational',
    nextAttemptAt: 'operational',
    message: 'operational!clear',
    appliedAt: 'operational',
    requiresConfirmation: 'operational',
    createdAt: 'operational',
  }, {
    links: {person: ['personId'], account: ['accountId']},
    erasure: 'pseudonymize',
    why: "Kept as the record of what was done to the account; the before and after attribute values and the message are cleared.",
  }),
  ProvisionException: table('runs', {
    id: 'identity',
    tenantId: 'none',
    runId: 'operational',
    personId: 'identity',
    targetSystemId: 'operational',
    kind: 'operational',
    message: 'operational!literal:[erased]',
    createdAt: 'operational',
  }, {
    links: {person: ['personId']},
    erasure: 'pseudonymize',
    why: "The message names the person and is replaced.",
  }),
  DriftFinding: table('runs', {
    id: 'identity',
    tenantId: 'none',
    targetSystemId: 'operational',
    runId: 'operational',
    accountId: 'identity',
    entitlementId: 'operational',
    subjectAnchor: 'identity',
    kind: 'operational',
    detail: 'operational!clear',
    status: 'operational',
    fingerprint: 'operational',
    firstSeenAt: 'operational',
    lastSeenAt: 'operational',
  }, {
    links: {account: ['accountId']},
    erasure: 'pseudonymize',
    why: "The detail (target attribute values) is cleared.",
  }),
  AutomateSettings: table('configuration', {
    id: 'none',
    tenantId: 'none',
    sweepSchedule: 'none',
    sweepThresholdPercent: 'none',
    perProductSweepThresholdPercent: 'none',
    personPopulationDropPercent: 'none',
    fulfilmentSlaHours: 'none',
    expiryWarningDays: 'none',
    preHireHorizonDays: 'none',
    maxDelegationDays: 'none',
    maxApprovers: 'none',
    delegatedBulkLimit: 'none',
    lastAppliedSweepAt: 'none',
    personsWithActiveContractAtLastSweep: 'none',
    createdAt: 'none',
    updatedAt: 'none',
  }),
  DelegatedTask: table('configuration', {
    id: 'none',
    tenantId: 'none',
    name: 'none',
    description: 'none',
    actionKey: 'none',
    formSchema: 'none',
    audienceCondition: 'none',
    enabled: 'none',
    createdAt: 'none',
    updatedAt: 'none',
  }),
  DelegatedTaskRun: table('requests', {
    id: 'identity',
    tenantId: 'none',
    taskId: 'operational',
    runByUserId: 'identity',
    subjectUserId: 'identity',
    values: 'operational!clear',
    outcome: 'operational',
    message: 'operational!literal:[erased]',
    createdAt: 'operational',
  }, {
    links: {user: ['subjectUserId', 'runByUserId']},
    erasure: 'pseudonymize',
    why: "The submitted form values are cleared.",
  }),
  Product: table('configuration', {
    id: 'none',
    tenantId: 'none',
    name: 'none',
    slug: 'none',
    description: 'none',
    category: 'none',
    iconUrl: 'none',
    requestInstructions: 'none',
    kind: 'none',
    audienceCondition: 'none',
    workflowId: 'none',
    formSchema: 'none',
    durationMode: 'none',
    defaultDurationDays: 'none',
    maxDurationDays: 'none',
    ownerPersonId: 'identity',
    ownerGroupId: 'none',
    status: 'none',
    createdAt: 'none',
    updatedAt: 'none',
  }, {
    links: {person: ['ownerPersonId']},
    erasure: 'retain',
    why: "Configuration naming the person as an owner.",
  }),
  ProductGrant: table('configuration', {
    id: 'none',
    tenantId: 'none',
    productId: 'none',
    resourceType: 'none',
    resourceId: 'none',
    targetSystemId: 'none',
    optional: 'none',
  }),
  ApprovalWorkflow: table('configuration', {
    id: 'none',
    tenantId: 'none',
    name: 'none',
    description: 'none',
    enabled: 'none',
    createdAt: 'none',
    updatedAt: 'none',
  }),
  ApprovalStage: table('configuration', {
    id: 'none',
    tenantId: 'none',
    workflowId: 'none',
    sequence: 'none',
    name: 'none',
    selector: 'none',
    selectorConfig: 'none',
    quorum: 'none',
    fallbackSelector: 'none',
    fallbackConfig: 'none',
    slaHours: 'none',
    onTimeout: 'none',
    escalationSelector: 'none',
    escalationConfig: 'none',
    expiryHours: 'none',
  }),
  AccessRequest: table('requests', {
    id: 'identity',
    tenantId: 'none',
    productId: 'operational',
    subjectPersonId: 'identity',
    requestedByUserId: 'identity',
    requestedByPersonId: 'identity',
    origin: 'operational',
    resourceType: 'operational',
    resourceId: 'operational',
    justification: 'operational!clear',
    formValues: 'operational!clear',
    requestedDurationDays: 'operational',
    replacesGrantId: 'operational',
    status: 'operational',
    statusReason: 'operational!clear',
    submittedAt: 'operational',
    decidedAt: 'operational',
    fulfilledAt: 'operational',
    dispatchedAt: 'operational',
  }, {
    links: {person: ['subjectPersonId', 'requestedByPersonId'], user: ['requestedByUserId']},
    erasure: 'pseudonymize',
    why: "Kept as access-governance evidence (who asked for what, and the outcome); the justification and form values the person typed are cleared.",
  }),
  RequestItem: table('requests', {
    id: 'identity',
    tenantId: 'none',
    requestId: 'operational',
    resourceType: 'operational',
    resourceId: 'operational',
    targetSystemId: 'operational',
    status: 'operational',
    provisionActionId: 'operational',
    grantId: 'operational',
    message: 'operational',
  }),
  ApprovalStep: table('requests', {
    id: 'identity',
    tenantId: 'none',
    requestId: 'operational',
    sequence: 'operational',
    stageSnapshot: 'operational',
    status: 'operational',
    openedAt: 'operational',
    closedAt: 'operational',
    slaDueAt: 'operational',
    escalatedAt: 'operational',
    lastRemindedAt: 'operational',
  }),
  ApprovalStepApprover: table('requests', {
    id: 'identity',
    tenantId: 'none',
    stepId: 'operational',
    personId: 'identity',
    via: 'operational',
    onBehalfOfPersonId: 'identity',
    addedAt: 'operational',
  }, {
    links: {person: ['personId', 'onBehalfOfPersonId']},
    erasure: 'retain',
    why: "Identifiers only.",
  }),
  ApprovalDecision: table('requests', {
    id: 'identity',
    tenantId: 'none',
    stepId: 'operational',
    personId: 'identity',
    userId: 'identity',
    decision: 'operational',
    comment: 'operational',
    shortenedToDays: 'operational',
    via: 'operational',
    onBehalfOfPersonId: 'identity',
    decidedAt: 'operational',
  }, {
    links: {person: ['personId', 'onBehalfOfPersonId'], user: ['userId']},
    erasure: 'retain',
    why: "Append-only at the database (no update, no delete): an approval decision is access-governance evidence. The comment is retained; it is also in the audit log.",
  }),
  ApprovalDelegation: table('requests', {
    id: 'identity',
    tenantId: 'none',
    delegatorPersonId: 'identity',
    delegatePersonId: 'identity',
    category: 'operational',
    startsAt: 'operational',
    endsAt: 'operational',
    createdByUserId: 'identity',
    revokedAt: 'operational',
    createdAt: 'operational',
  }, {
    links: {person: ['delegatorPersonId', 'delegatePersonId']},
    erasure: 'retain',
    why: "Identifiers and dates only.",
  }),
  AccessGrant: table('requests', {
    id: 'identity',
    tenantId: 'none',
    subjectPersonId: 'identity',
    resourceType: 'operational',
    resourceId: 'operational',
    targetSystemId: 'operational',
    origin: 'operational',
    requestId: 'operational',
    productId: 'operational',
    startsAt: 'operational',
    endsAt: 'operational',
    status: 'operational',
    statusReason: 'operational',
    needsReview: 'operational',
    reviewReason: 'operational',
    reviewedAt: 'operational',
    supersededByGrantId: 'operational',
    approvedByPersonId: 'identity',
    writtenRowIds: 'operational',
    createdAt: 'operational',
    endedAt: 'operational',
  }, {
    links: {person: ['subjectPersonId', 'approvedByPersonId']},
    erasure: 'retain',
    why: "Access-governance evidence: what was granted, when and on whose approval. Identifiers only.",
  }),
  ResourceOwner: table('configuration', {
    id: 'none',
    tenantId: 'none',
    resourceType: 'none',
    resourceId: 'none',
    ownerPersonId: 'identity',
    ownerGroupId: 'none',
    createdAt: 'none',
    updatedAt: 'none',
  }, {
    links: {person: ['ownerPersonId']},
    erasure: 'retain',
    why: "Configuration naming the person as an owner; reassign it before or after the erasure.",
  }),
  ResourceDelegation: table('configuration', {
    id: 'none',
    tenantId: 'none',
    resourceType: 'none',
    resourceId: 'none',
    delegatePersonId: 'identity',
    delegateGroupId: 'none',
    capabilities: 'none',
    audienceCondition: 'none',
    startsAt: 'none',
    endsAt: 'none',
    createdByUserId: 'identity',
    createdAt: 'none',
  }, {
    links: {person: ['delegatePersonId']},
    erasure: 'retain',
    why: "Configuration naming the person as a delegate.",
  }),
  ExpirySweep: table('runs', {
    id: 'identity',
    tenantId: 'none',
    status: 'operational',
    startedAt: 'operational',
    finishedAt: 'operational',
    expireCount: 'operational',
    lapseCount: 'operational',
    reviewFlagCount: 'operational',
    personsWithActiveContract: 'operational',
    personsUnprocessable: 'operational',
    internalGrantsInTenant: 'operational',
    requiresConfirmation: 'operational',
    blockedReason: 'operational',
    confirmedByUserId: 'identity',
    error: 'operational',
  }),
  SweepAction: table('runs', {
    id: 'identity',
    tenantId: 'none',
    sweepId: 'operational',
    grantId: 'operational',
    kind: 'operational',
    productId: 'operational',
    subjectPersonId: 'identity',
    resourceType: 'operational',
    resourceId: 'operational',
    targetSystemId: 'operational',
    status: 'operational',
    provisionActionId: 'operational',
    message: 'operational',
  }, {
    links: {person: ['subjectPersonId']},
    erasure: 'retain',
    why: "Identifiers only.",
  }),
  SweepException: table('runs', {
    id: 'identity',
    tenantId: 'none',
    sweepId: 'operational',
    personId: 'identity',
    kind: 'operational',
    message: 'operational!literal:[erased]',
    createdAt: 'operational',
  }, {
    links: {person: ['personId']},
    erasure: 'pseudonymize',
    why: "The message can name the person and is replaced.",
  }),
  NotificationOutbox: table('notifications', {
    id: 'identity',
    tenantId: 'none',
    template: 'operational',
    to: 'contact!pseudonym-email',
    vars: 'operational!clear',
    requestId: 'operational',
    userId: 'identity',
    attempts: 'operational',
    lastError: 'operational!literal:erased by a data-subject request',
    sentAt: 'operational',
    digest: 'operational',
    createdAt: 'operational',
  }, {
    links: {user: ['userId'], identifier: ['to']},
    erasure: 'pseudonymize',
    why: "The recipient address and the template variables are replaced, and an unsent message is stopped.",
  }),
  WebhookEndpoint: table('configuration', {
    id: 'none',
    tenantId: 'none',
    name: 'none',
    url: 'none',
    enabled: 'none',
    events: 'none',
    createdAt: 'none',
    updatedAt: 'none',
  }),
  WebhookDelivery: table('notifications', {
    id: 'identity',
    tenantId: 'none',
    endpointId: 'operational',
    event: 'operational',
    payload: 'operational',
    attempts: 'operational',
    nextAttemptAt: 'operational',
    deliveredAt: 'operational',
    lastStatus: 'operational',
    lastError: 'operational',
    createdAt: 'operational',
  }),
  NotificationPreference: table('notifications', {
    id: 'identity',
    tenantId: 'none',
    userId: 'identity',
    mode: 'operational',
    updatedAt: 'operational',
  }, {
    links: {user: ['userId']},
    erasure: 'retain',
    why: "A delivery mode only.",
  }),
  GovernSettings: table('configuration', {
    id: 'none',
    tenantId: 'none',
    snapshotSchedule: 'none',
    snapshotRetentionDays: 'none',
    defaultFreshnessSlaHours: 'none',
    maxSnapshotAgeDays: 'none',
    batchThresholdPercent: 'none',
    perResourceThresholdPercent: 'none',
    personPopulationDropPercent: 'none',
    minimumCoveragePercent: 'none',
    bulkCertifyLimit: 'none',
    dispatchSlaHours: 'none',
    privilegedRecertifyDays: 'none',
    maxExceptionDays: 'none',
    exceptionWarningDays: 'none',
    minReciprocalDecisions: 'none',
    reciprocityWindowDays: 'none',
    lastAppliedBatchAt: 'none',
    personsWithActiveContractAtLastBatch: 'none',
    createdAt: 'none',
    updatedAt: 'none',
  }),
  GovernSourcePolicy: table('configuration', {
    id: 'none',
    tenantId: 'none',
    sourceKind: 'none',
    sourceId: 'none',
    freshnessSlaHours: 'none',
    inDefaultScope: 'none',
    createdAt: 'none',
    updatedAt: 'none',
  }),
  ResourceClassification: table('configuration', {
    id: 'none',
    tenantId: 'none',
    systemId: 'none',
    resourceKind: 'none',
    resourceId: 'none',
    privileged: 'none',
    note: 'none',
    setByUserId: 'identity',
    setAt: 'none',
  }),
  AccessSnapshot: table('governance', {
    id: 'identity',
    tenantId: 'none',
    kind: 'operational',
    status: 'operational',
    startedAt: 'operational',
    finishedAt: 'operational',
    asOf: 'operational',
    scope: 'operational',
    holdingCount: 'operational',
    unattributableCount: 'operational',
    coverageGapCount: 'operational',
    unattributedAccountCount: 'operational',
    personCount: 'operational',
    personsWithActiveContract: 'operational',
    countsByResourceKind: 'operational',
    error: 'operational',
  }),
  SnapshotSource: table('governance', {
    id: 'identity',
    tenantId: 'none',
    snapshotId: 'operational',
    sourceKind: 'operational',
    sourceId: 'operational',
    sourceName: 'operational',
    lastRunId: 'operational',
    lastSuccessfulReadAt: 'operational',
    lastAttemptedReadAt: 'operational',
    completeness: 'operational',
    staleness: 'operational',
    freshnessSlaHours: 'operational',
    gapCount: 'operational',
  }),
  Holding: table('governance', {
    id: 'identity',
    tenantId: 'none',
    snapshotId: 'operational',
    subjectKey: 'identity',
    personId: 'identity',
    accountRef: 'identity',
    systemKind: 'operational',
    systemId: 'operational',
    resourceKind: 'operational',
    resourceId: 'operational',
    resourceName: 'operational',
    state: 'operational',
    privileged: 'operational',
    observedAt: 'operational',
    observedVia: 'operational',
    firstSeenAt: 'operational',
    attributionCount: 'operational',
    unattributable: 'operational',
  }, {
    links: {person: ['personId']},
    erasure: 'retain',
    why: "Access-review evidence frozen in a snapshot; removed with the snapshot by the Govern snapshot retention.",
  }),
  HoldingAttribution: table('governance', {
    id: 'identity',
    tenantId: 'none',
    holdingId: 'operational',
    kind: 'operational',
    refType: 'operational',
    refId: 'operational',
    detail: 'operational',
    resolvedAt: 'operational',
  }),
  CoverageGap: table('governance', {
    id: 'identity',
    tenantId: 'none',
    snapshotId: 'operational',
    kind: 'operational',
    systemKind: 'operational',
    systemId: 'operational',
    resourceId: 'operational',
    personId: 'identity',
    accountRef: 'identity',
    reason: 'operational',
    sourceRunId: 'operational',
  }, {
    links: {person: ['personId']},
    erasure: 'retain',
    why: "Snapshot evidence; removed with the snapshot.",
  }),
  HoldingEvent: table('governance', {
    id: 'identity',
    tenantId: 'none',
    fromSnapshotId: 'operational',
    toSnapshotId: 'operational',
    subjectKey: 'identity',
    personId: 'identity',
    accountRef: 'identity',
    systemId: 'operational',
    resourceKind: 'operational',
    resourceId: 'operational',
    resourceName: 'operational',
    change: 'operational',
    beforeAttributions: 'operational',
    afterAttributions: 'operational',
    auditEventSequence: 'operational',
    explained: 'operational',
  }, {
    links: {person: ['personId']},
    erasure: 'retain',
    why: "Snapshot evidence; removed with the snapshot.",
  }),
  HoldingCertification: table('governance', {
    id: 'identity',
    tenantId: 'none',
    subjectRefType: 'operational',
    subjectRefId: 'operational',
    systemId: 'operational',
    resourceKind: 'operational',
    resourceId: 'operational',
    lastCertifiedAt: 'operational',
    lastCertifiedByPersonId: 'identity',
    lastCampaignId: 'operational',
    lastDecisionId: 'operational',
  }, {
    links: {person: ['lastCertifiedByPersonId']},
    erasure: 'retain',
    why: "Certification evidence: who last certified an access.",
  }),
  AccountAttribution: table('governance', {
    id: 'identity',
    tenantId: 'none',
    systemId: 'operational',
    accountRef: 'identity',
    proposedPersonId: 'identity',
    method: 'operational',
    confidence: 'operational',
    status: 'operational',
    decidedByUserId: 'identity',
    decidedAt: 'operational',
    decidedReason: 'operational',
    createdAt: 'operational',
  }, {
    links: {person: ['proposedPersonId']},
    erasure: 'retain',
    why: "Identifiers only.",
  }),
  GovernFinding: table('governance', {
    id: 'identity',
    tenantId: 'none',
    kind: 'operational',
    severity: 'operational',
    subjectRefType: 'operational',
    subjectRefId: 'operational',
    detail: 'operational',
    driftFindingId: 'operational',
    status: 'operational',
    ownerPersonId: 'identity',
    dueAt: 'operational',
    acceptedReason: 'operational',
    acceptedUntil: 'operational',
    resolvedBySnapshotId: 'operational',
    resolvedAt: 'operational',
    firstSeenAt: 'operational',
    lastSeenAt: 'operational',
  }, {
    links: {person: ['ownerPersonId']},
    erasure: 'retain',
    why: "Identifiers only.",
  }),
  RemediationItem: table('governance', {
    id: 'identity',
    tenantId: 'none',
    kind: 'operational',
    ownerPersonId: 'identity',
    dueAt: 'operational',
    findingId: 'operational',
    campaignItemId: 'operational',
    description: 'operational',
    deepLink: 'operational',
    status: 'operational',
    resolutionComment: 'operational',
    resolvedByUserId: 'identity',
    resolvedAt: 'operational',
    createdAt: 'operational',
  }, {
    links: {person: ['ownerPersonId']},
    erasure: 'retain',
    why: "Identifiers only.",
  }),
  EvidencePack: table('governance', {
    id: 'identity',
    tenantId: 'none',
    kind: 'operational',
    scope: 'operational',
    snapshotId: 'operational',
    campaignId: 'operational',
    chainHeadSequence: 'operational',
    chainHeadHash: 'operational',
    chainVerificationResult: 'operational',
    chainFromSequence: 'operational',
    chainToSequence: 'operational',
    digest: 'operational',
    storageRef: 'operational',
    byteLength: 'operational',
    createdByUserId: 'identity',
    createdAt: 'operational',
  }),
  AuditCheckpoint: table('audit', {
    id: 'audit',
    tenantId: 'none',
    sequence: 'audit',
    hash: 'audit',
    verifiedAt: 'audit',
    signature: 'audit',
    keyId: 'audit',
  }),
  AuditChainCheck: table('audit', {
    id: 'audit',
    tenantId: 'none',
    fromSequence: 'audit',
    toSequence: 'audit',
    result: 'audit',
    brokenAtSequence: 'audit',
    startedAt: 'audit',
    durationMs: 'audit',
    mode: 'audit',
  }),
  AuditAnchor: table('audit', {
    id: 'audit',
    tenantId: 'none',
    sequence: 'audit',
    hash: 'audit',
    anchoredAt: 'audit',
    method: 'audit',
    receipt: 'audit',
    status: 'audit',
    error: 'audit',
  }),
  Campaign: table('governance', {
    id: 'identity',
    tenantId: 'none',
    name: 'operational',
    description: 'operational',
    scope: 'operational',
    snapshotId: 'operational',
    rebasedFromSnapshotId: 'operational',
    reviewerSelector: 'operational',
    reviewerConfig: 'operational',
    fallbackSelector: 'operational',
    fallbackConfig: 'operational',
    ownerPersonId: 'identity',
    opensAt: 'operational',
    dueAt: 'operational',
    originalDueAt: 'operational',
    extensionCount: 'operational',
    recurrence: 'operational',
    allowBulkCertify: 'operational',
    status: 'operational',
    totalItems: 'operational',
    certifiedItems: 'operational',
    revokedItems: 'operational',
    revokeDecidedItems: 'operational',
    dispatchedItems: 'operational',
    failedItems: 'operational',
    mootItems: 'operational',
    undecidedItems: 'operational',
    blockedItems: 'operational',
    requiresChangeItems: 'operational',
    coveragePercent: 'operational',
    createdAt: 'operational',
    updatedAt: 'operational',
  }, {
    links: {person: ['ownerPersonId']},
    erasure: 'retain',
    why: "Identifiers only.",
  }),
  CampaignItem: table('governance', {
    id: 'identity',
    tenantId: 'none',
    campaignId: 'operational',
    holdingSnapshotId: 'operational',
    subjectKey: 'identity',
    personId: 'identity',
    accountRef: 'identity',
    systemId: 'operational',
    resourceKind: 'operational',
    resourceId: 'operational',
    resourceName: 'operational',
    attributions: 'operational',
    observedAt: 'operational',
    coverageStatus: 'operational',
    riskFlags: 'operational',
    status: 'operational',
    statusReason: 'operational',
    outcomeRef: 'operational',
    createdAt: 'operational',
  }, {
    links: {person: ['personId']},
    erasure: 'retain',
    why: "Access-review evidence.",
  }),
  CampaignItemReviewer: table('governance', {
    id: 'identity',
    tenantId: 'none',
    itemId: 'operational',
    personId: 'identity',
    via: 'operational',
    assignedAt: 'operational',
    unassignedAt: 'operational',
    unassignedReason: 'operational',
    lastRemindedAt: 'operational',
    openedAt: 'operational',
  }, {
    links: {person: ['personId']},
    erasure: 'retain',
    why: "Access-review evidence.",
  }),
  CampaignDecision: table('governance', {
    id: 'identity',
    tenantId: 'none',
    itemId: 'operational',
    personId: 'identity',
    decidedByUserId: 'identity',
    decision: 'operational',
    comment: 'operational',
    itemOpenedAt: 'operational',
    decidedAt: 'operational',
    neverOpened: 'operational',
    viaBulk: 'operational',
    bulkSize: 'operational',
    sessionDecisionOrdinal: 'operational',
    coverageAtDecision: 'operational',
  }, {
    links: {person: ['personId']},
    erasure: 'retain',
    why: "Append-only at the database: a review decision is access-governance evidence.",
  }),
  ReviewQualitySignal: table('governance', {
    id: 'identity',
    tenantId: 'none',
    campaignId: 'operational',
    personId: 'identity',
    itemsAssigned: 'operational',
    itemsDecided: 'operational',
    certifiedShare: 'operational',
    medianIntervalMs: 'operational',
    bulkShare: 'operational',
    largestBurst: 'operational',
    largestBurstMs: 'operational',
    neverOpenedShare: 'operational',
    computedAt: 'operational',
  }, {
    links: {person: ['personId']},
    erasure: 'retain',
    why: "Aggregate numbers about a reviewer.",
  }),
  RevocationBatch: table('governance', {
    id: 'identity',
    tenantId: 'none',
    campaignId: 'operational',
    status: 'operational',
    proposedCount: 'operational',
    skippedCount: 'operational',
    dispatchedCount: 'operational',
    confirmedCount: 'operational',
    appliedCount: 'operational',
    failedCount: 'operational',
    requiresChangeCount: 'operational',
    cancelledCount: 'operational',
    requiresConfirmation: 'operational',
    blockedReason: 'operational',
    confirmedByUserId: 'identity',
    startedAt: 'operational',
    finishedAt: 'operational',
    error: 'operational',
  }),
  RevocationDispatch: table('governance', {
    id: 'identity',
    tenantId: 'none',
    batchId: 'operational',
    itemId: 'operational',
    holdingDescriptor: 'operational',
    route: 'operational',
    status: 'operational',
    grantId: 'operational',
    revocationOrderId: 'operational',
    remediationItemId: 'operational',
    message: 'operational',
    sequence: 'operational',
    dispatchedAt: 'operational',
    confirmedAt: 'operational',
    appliedAt: 'operational',
  }),
  RevocationOrder: table('governance', {
    id: 'identity',
    tenantId: 'none',
    targetSystemId: 'operational',
    accountId: 'identity',
    entitlementId: 'operational',
    decidedByPersonId: 'identity',
    campaignDecisionId: 'operational',
    decidedByPersonName: 'identity!literal:Erased person',
    campaignName: 'operational',
    reason: 'operational',
    status: 'operational',
    cancelledReason: 'operational',
    createdAt: 'operational',
    plannedAt: 'operational',
    appliedAt: 'operational',
  }, {
    links: {person: ['decidedByPersonId']},
    erasure: 'pseudonymize',
    why: "The decider's name, copied onto the order when it was made, is replaced.",
  }),
  BusinessFunction: table('configuration', {
    id: 'none',
    tenantId: 'none',
    name: 'none',
    description: 'none',
    ownerPersonId: 'identity',
    createdAt: 'none',
    updatedAt: 'none',
  }, {
    links: {person: ['ownerPersonId']},
    erasure: 'retain',
    why: "Configuration naming the person as an owner.",
  }),
  BusinessFunctionResource: table('configuration', {
    id: 'none',
    tenantId: 'none',
    functionId: 'none',
    systemId: 'none',
    resourceKind: 'none',
    resourceId: 'none',
  }),
  SodRule: table('configuration', {
    id: 'none',
    tenantId: 'none',
    name: 'none',
    functionAId: 'none',
    functionBId: 'none',
    severity: 'none',
    rationale: 'none',
    exceptionWorkflowId: 'none',
    enabled: 'none',
    createdAt: 'none',
    updatedAt: 'none',
  }),
  SodViolation: table('governance', {
    id: 'identity',
    tenantId: 'none',
    ruleId: 'operational',
    personId: 'identity',
    holdingsA: 'operational',
    holdingsB: 'operational',
    contractsA: 'operational',
    contractsB: 'operational',
    severity: 'operational',
    status: 'operational',
    exceptionId: 'operational',
    firstSeenAt: 'operational',
    lastSeenAt: 'operational',
    lastSnapshotId: 'operational',
  }, {
    links: {person: ['personId']},
    erasure: 'retain',
    why: "Risk evidence; identifiers only.",
  }),
  SodException: table('governance', {
    id: 'identity',
    tenantId: 'none',
    ruleId: 'operational',
    personId: 'identity',
    violationId: 'operational',
    justification: 'operational',
    compensatingControl: 'operational',
    basisContractIds: 'operational',
    approvalRequestId: 'operational',
    approvedByPersonId: 'identity',
    startsAt: 'operational',
    endsAt: 'operational',
    status: 'operational',
    revokedReason: 'operational',
    revokedByUserId: 'identity',
    createdAt: 'operational',
    updatedAt: 'operational',
  }, {
    links: {person: ['personId', 'approvedByPersonId']},
    erasure: 'retain',
    why: "Risk-acceptance evidence, including its justification.",
  }),
  RateLimitBucket: table('protocol', {
    key: 'authentication',
    hits: 'none',
    resetAt: 'none',
  }),
  DataExport: table('exports', {
    id: 'identity',
    tenantId: 'none',
    kind: 'operational',
    status: 'operational',
    params: 'operational',
    format: 'operational',
    requestedByUserId: 'identity',
    requestedViaToken: 'operational',
    requestedAt: 'operational',
    ttlHours: 'operational',
    startedAt: 'operational',
    completedAt: 'operational',
    expiresAt: 'operational',
    authorityFingerprint: 'operational',
    rowCount: 'operational',
    byteLength: 'operational',
    sha256: 'operational',
    filename: 'operational',
    contentType: 'operational',
    error: 'operational',
    ciphertext: 'authentication#secret',
    iv: 'authentication#secret',
    tag: 'authentication#secret',
    wrappedDek: 'authentication#secret',
    dekIv: 'authentication#secret',
    dekTag: 'authentication#secret',
    revokedAt: 'operational',
    revokedByUserId: 'identity',
    purgedAt: 'operational',
    downloadCount: 'operational',
    lastDownloadedAt: 'operational',
    updatedAt: 'operational',
  }, {
    links: {user: ['requestedByUserId']},
    erasure: 'retain',
    why: "The record of who took which copy. An access bundle about the person that still holds a file has the file erased (see the erasure procedure).",
  }),
  AuditSavedView: table('exports', {
    id: 'identity',
    tenantId: 'none',
    userId: 'identity',
    name: 'operational',
    filters: 'operational',
    createdAt: 'operational',
    updatedAt: 'operational',
  }, {
    links: {user: ['userId']},
    erasure: 'delete',
    why: "The person's own saved search filters.",
  }),
  PrivacyCase: table('privacy', {
    id: 'identity',
    tenantId: 'none',
    personId: 'identity',
    reference: 'operational',
    status: 'operational',
    requestTypes: 'operational',
    reason: 'operational',
    receivedAt: 'operational',
    dueAt: 'operational',
    verificationMethod: 'operational',
    verificationAttestation: 'operational',
    verifiedByUserId: 'identity',
    openedByUserId: 'identity',
    openedAt: 'operational',
    accessExportId: 'operational',
    erasureStatus: 'operational',
    erasureRequestedByUserId: 'identity',
    erasureRequestedAt: 'operational',
    erasureApprovedByUserId: 'identity',
    erasureApprovedAt: 'operational',
    erasureApproverStepUpAt: 'operational',
    erasureCompletedAt: 'operational',
    erasureCancelledByUserId: 'identity',
    erasureCancelledAt: 'operational',
    erasureReceipt: 'operational',
    closedAt: 'operational',
    closedByUserId: 'identity',
    closureNote: 'operational',
    updatedAt: 'operational',
  }, {
    links: {person: ['personId']},
    erasure: 'retain',
    why: "The record that the request was received, verified and handled (accountability, GDPR art. 5(2)).",
  }),
};

/** Every table, by Prisma model name. */
export const DATA_INVENTORY: Readonly<Record<string, TableEntry>> = Object.fromEntries(
  Object.entries(RAW).map(([model, entry]) => [model, { model, ...entry }]),
);

export function inventoryEntry(model: string): TableEntry {
  const entry = DATA_INVENTORY[model];
  if (entry === undefined) throw new Error(`the data inventory has no entry for ${model}`);
  return entry;
}

/** The tables a data-subject search reads: every one that declares links. */
export function subjectLinkedTables(): TableEntry[] {
  return Object.values(DATA_INVENTORY).filter((entry) => entry.links !== null);
}

/** Whether a table holds any personal data at all. */
export function holdsPersonalData(entry: TableEntry): boolean {
  return entry.fields.some((field) => field.class !== 'none');
}

/**
 * A row as an access bundle may carry it: every column the inventory knows,
 * minus credential material. A column the inventory does not know is left out
 * too -- the structural test makes that impossible in a built tree, and a
 * bundle is the wrong place to discover it.
 */
export function projectForBundle(model: string, row: Record<string, unknown>): Record<string, unknown> {
  const entry = inventoryEntry(model);
  const out: Record<string, unknown> = {};
  for (const field of entry.fields) {
    if (field.secret) continue;
    if (Object.prototype.hasOwnProperty.call(row, field.name)) out[field.name] = row[field.name];
  }
  return out;
}
